import type { FoilMaterial } from "@/core/render/foil/types";

import manifestJson from "./manifest.json";

/**
 * Lorcana card-effect materials, verbatim from the mobile app bundle.
 *
 * Generated by `scripts/effects-dump/dump_unity.py --pack lorcana` — regenerate
 * rather than edit. Companion `.frag` files live under `public/foil/lorcana/shaders/`.
 */

const MATERIALS = manifestJson as Record<string, FoilMaterial>;

export const LORCANA_MATERIAL_NAMES = Object.keys(MATERIALS).sort();

export function lorcanaMaterial(name: string): FoilMaterial | null {
  return MATERIALS[name] ?? null;
}

/**
 * Fragments that actually sample `_SecondTopLayerMask`.
 *
 * The dump also has `USESECONDTOPLAYER` + `VARNISHTYPE_NONE` / `HIGHGLOSS`
 * filenames where the second sampler is compiled out (`Xhlslcc_UnusedX_*`) —
 * those do not draw a second coat. Only HotFoil siblings keep the sampler.
 */
const ACTIVE_SECOND_TOP_LAYER_FRAGMENTS = new Set([
  "CardFoilLore___FOILOFFSETSRAINBOW___HOTFOILSURFACE_COLORRAINBOW___USESECONDTOPLAYER___VARNISHTYPE_HOTFOIL.frag",
  "CardFoilLore___FOILOFFSETSRAINBOW___HOTFOILSURFACE_COLORRAINBOW___USESECONDTOPLAYER___VARNISHTYPE_HOTFOIL___SCROLLMODE_TIME.frag",
  "CardFoilLore___FOILOFFSETSRAINBOW___HOTFOILSURFACE_METALLIC___USESECONDTOPLAYER___VARNISHTYPE_HOTFOIL.frag",
  "CardFoilLore___FOILOFFSETSRAINBOW___HOTFOILSURFACE_METALLIC___USESECONDTOPLAYER___VARNISHTYPE_HOTFOIL___SCROLLMODE_TIME.frag",
  "CardFoilLore___FOILOFFSETSRAINBOW___HOTFOILSURFACE_SNOW___USESECONDTOPLAYER___VARNISHTYPE_HOTFOIL.frag",
  "CardFoilLore___FOILOFFSETSRAINBOW___HOTFOILSURFACE_SNOW___USESECONDTOPLAYER___VARNISHTYPE_HOTFOIL___SCROLLMODE_TIME.frag",
  "CardFoilLore___HOTFOILSURFACE_METALLIC___USESECONDTOPLAYER___VARNISHTYPE_HOTFOIL.frag",
  "CardFoilLore___HOTFOILSURFACE_METALLIC___USESECONDTOPLAYER___VARNISHTYPE_HOTFOIL___SCROLLMODE_TIME.frag",
]);

/**
 * The HotFoil sibling that enables the second stamp, or `null` when this
 * material has no such compiled variant (Silver, Glitter, varnish-none…).
 */
export function secondTopLayerFragment(fragment: string): string | null {
  if (fragment.includes("USESECONDTOPLAYER")) {
    return ACTIVE_SECOND_TOP_LAYER_FRAGMENTS.has(fragment) ? fragment : null;
  }
  if (!fragment.includes("___VARNISHTYPE_")) return null;
  const sibling = fragment.replace(
    "___VARNISHTYPE_",
    "___USESECONDTOPLAYER___VARNISHTYPE_",
  );
  return ACTIVE_SECOND_TOP_LAYER_FRAGMENTS.has(sibling) ? sibling : null;
}

/**
 * Material as dumped, or the `USESECONDTOPLAYER` sibling when the print
 * carries a second varnish mask and a matching fragment exists.
 */
export function lorcanaMaterialForPrint(
  name: string,
  options: { secondVarnishMaskUrl?: string | null } = {},
): FoilMaterial | null {
  const base = lorcanaMaterial(name);
  if (!base) return null;
  if (!options.secondVarnishMaskUrl) return base;

  const sibling = secondTopLayerFragment(base.fragment);
  if (!sibling || sibling === base.fragment) return base;

  const siblingTime = base.fragmentTime
    ? secondTopLayerFragment(base.fragmentTime)
    : null;

  return {
    ...base,
    fragment: sibling,
    fragmentTime: siblingTime ?? base.fragmentTime,
    keywords: base.keywords.includes("_USESECONDTOPLAYER")
      ? base.keywords
      : base.keywords.includes("USESECONDTOPLAYER")
        ? base.keywords
        : [...base.keywords, "_USESECONDTOPLAYER"],
    textures: {
      ...base.textures,
      _SecondTopLayerMask: { role: "secondVarnishMask" },
    },
    colors: {
      ...base.colors,
      _SecondHotFoilColor:
        base.colors._SecondHotFoilColor ??
        base.colors._HotFoilColor ??
        [1, 1, 1, 1],
    },
  };
}
