import type { FoilMaterial } from "@/core/render/foil/types";
import { hotFoilStampUniforms } from "@/core/render/foil/hotFoilStamp";

import manifestJson from "./manifest.json";

export { hotFoilStampUniforms };

/**
 * Lorcana card-effect materials, verbatim from the mobile app bundle.
 *
 * Generated by `pnpm foil:lorcana -- --providers lorcanamobile --apk …` —
 * companion `.frag` files live under `data/lorcana/foil/shaders/`.
 */

const MATERIALS = manifestJson as Record<string, FoilMaterial>;

export const LORCANA_MATERIAL_NAMES = Object.keys(MATERIALS).sort();

/**
 * Dump leftovers: HotFoil bases list `_SecondTopLayerMask` even when the
 * fragment compiles that sampler out (`Xhlslcc_UnusedX_*`). Requiring a second
 * mask URL then blocks WebGL for every HotFoil print that has no second coat
 * (all but ~2 cards in the catalogue). Strip the phantom role unless the
 * fragment is a real `USESECONDTOPLAYER` sibling.
 */
function withoutPhantomSecondTopLayer(material: FoilMaterial): FoilMaterial {
  const binding = material.textures._SecondTopLayerMask;
  if (!binding || binding.role !== "secondVarnishMask") return material;
  if (material.fragment.includes("USESECONDTOPLAYER")) return material;
  const { _SecondTopLayerMask: _removed, ...textures } = material.textures;
  return { ...material, textures };
}

export function lorcanaMaterial(name: string): FoilMaterial | null {
  const material = MATERIALS[name];
  return material ? withoutPhantomSecondTopLayer(material) : null;
}

/**
 * Fragments that actually sample `_SecondTopLayerMask`.
 *
 * The dump also has `USESECONDTOPLAYER` + `VARNISHTYPE_NONE` / `HIGHGLOSS`
 * filenames where the second sampler is compiled out (`Xhlslcc_UnusedX_*`) —
 * those do not draw a second coat. Only HotFoil siblings keep the sampler.
 */
const ACTIVE_SECOND_TOP_LAYER_FRAGMENTS = new Set([
  "CardFoilLore___FOILOFFSETSRAINBOW___HOTFOILSURFACE_COLORRAINBOW___USESECONDTOPLAYER___VARNISHTYPE_HOTFOIL.frag",
  "CardFoilLore___FOILOFFSETSRAINBOW___HOTFOILSURFACE_COLORRAINBOW___USESECONDTOPLAYER___VARNISHTYPE_HOTFOIL___SCROLLMODE_TIME.frag",
  "CardFoilLore___FOILOFFSETSRAINBOW___HOTFOILSURFACE_METALLIC___USESECONDTOPLAYER___VARNISHTYPE_HOTFOIL.frag",
  "CardFoilLore___FOILOFFSETSRAINBOW___HOTFOILSURFACE_METALLIC___USESECONDTOPLAYER___VARNISHTYPE_HOTFOIL___SCROLLMODE_TIME.frag",
  "CardFoilLore___FOILOFFSETSRAINBOW___HOTFOILSURFACE_SNOW___USESECONDTOPLAYER___VARNISHTYPE_HOTFOIL.frag",
  "CardFoilLore___FOILOFFSETSRAINBOW___HOTFOILSURFACE_SNOW___USESECONDTOPLAYER___VARNISHTYPE_HOTFOIL___SCROLLMODE_TIME.frag",
  "CardFoilLore___HOTFOILSURFACE_METALLIC___USESECONDTOPLAYER___VARNISHTYPE_HOTFOIL.frag",
  "CardFoilLore___HOTFOILSURFACE_METALLIC___USESECONDTOPLAYER___VARNISHTYPE_HOTFOIL___SCROLLMODE_TIME.frag",
]);

/**
 * Second CalculateVarnishLayers DistortionTex — only live in USESECONDTOPLAYER
 * siblings. Base HotFoil materials bind the primary node; the sibling needs
 * this slot too (same varnishsurface). Without it WebGL samples solid black.
 */
const SECOND_VARNISH_DISTORTION_TEX =
  "_CalculateVarnishLayers_b94d50f356ab4aa9980ffc008846a1cd_DistortionTex_3454849507_Texture2D";

const VARNISH_DISTORTION_TEX_RE =
  /^_CalculateVarnishLayers_.*_DistortionTex_/;

/**
 * The HotFoil sibling that enables the second stamp, or `null` when this
 * material has no such compiled variant (Silver, Glitter, varnish-none…).
 */
export function secondTopLayerFragment(fragment: string): string | null {
  if (fragment.includes("USESECONDTOPLAYER")) {
    return ACTIVE_SECOND_TOP_LAYER_FRAGMENTS.has(fragment) ? fragment : null;
  }
  if (!fragment.includes("___VARNISHTYPE_")) return null;
  const sibling = fragment.replace(
    "___VARNISHTYPE_",
    "___USESECONDTOPLAYER___VARNISHTYPE_",
  );
  return ACTIVE_SECOND_TOP_LAYER_FRAGMENTS.has(sibling) ? sibling : null;
}

/**
 * Texture table for a USESECONDTOPLAYER sibling: second varnish mask role +
 * the DistortionTex the second CalculateVarnishLayers node samples.
 */
export function texturesForSecondTopLayer(
  textures: FoilMaterial["textures"],
): FoilMaterial["textures"] {
  const out: FoilMaterial["textures"] = {
    ...textures,
    _SecondTopLayerMask: { role: "secondVarnishMask" },
  };
  if (out[SECOND_VARNISH_DISTORTION_TEX]?.file) return out;
  const donorKey = Object.keys(out).find((key) =>
    VARNISH_DISTORTION_TEX_RE.test(key),
  );
  const donor = donorKey ? out[donorKey] : undefined;
  if (donor?.file) {
    out[SECOND_VARNISH_DISTORTION_TEX] = { ...donor };
  }
  return out;
}

/**
 * Material as dumped, or the `USESECONDTOPLAYER` sibling when the print
 * carries a second varnish mask and a matching fragment exists.
 */
export function lorcanaMaterialForPrint(
  name: string,
  options: { secondVarnishMaskUrl?: string | null } = {},
): FoilMaterial | null {
  const base = lorcanaMaterial(name);
  if (!base) return null;
  if (!options.secondVarnishMaskUrl) return base;

  const sibling = secondTopLayerFragment(base.fragment);
  if (!sibling || sibling === base.fragment) return base;

  const siblingTime = base.fragmentTime
    ? secondTopLayerFragment(base.fragmentTime)
    : null;

  return {
    ...base,
    fragment: sibling,
    fragmentTime: siblingTime ?? base.fragmentTime,
    keywords: base.keywords.includes("_USESECONDTOPLAYER")
      ? base.keywords
      : base.keywords.includes("USESECONDTOPLAYER")
        ? base.keywords
        : [...base.keywords, "_USESECONDTOPLAYER"],
    textures: texturesForSecondTopLayer(base.textures),
    colors: {
      ...base.colors,
      _SecondHotFoilColor:
        base.colors._SecondHotFoilColor ??
        base.colors._HotFoilColor ??
        base.colors._VarnishLightColor ??
        [1, 1, 1, 1],
    },
  };
}
