/**
 * Local-first Lorcana per-card assets under `/foil/lorcana/cards/{printKey}/`.
 *
 * Layout (scrape FR + EN + DE + IT):
 *   cards/{printKey}/{lang}/art.jpg|thumb.jpg|foil_mask.jpg|…
 *
 * Index is generated by `scripts/lorcana/scrape_cards.ts`. Client-safe: presence
 * comes from the JSON index, not `fs`.
 */

import cardsIndexJson from "./cards-index.json";

export type LorcanaCardLangFiles = {
  foilMask?: string;
  varnishMask?: string;
  secondVarnishMask?: string;
  art?: string;
  thumb?: string;
};

type PackLang = "fr" | "en" | "de" | "it";
const PACK_LANGS = ["fr", "en", "de", "it"] as const;
const DEFAULT_PACK_LANG: PackLang = "fr";

function isPackLang(value: unknown): value is PackLang {
  return (
    typeof value === "string" &&
    (PACK_LANGS as readonly string[]).includes(value)
  );
}

/** Per-language folders, plus optional legacy flat files at the print root. */
export type LorcanaCardPackEntry = LorcanaCardLangFiles &
  Partial<Record<PackLang, LorcanaCardLangFiles>>;

type CardsIndex = {
  cards: Record<string, LorcanaCardPackEntry>;
  languages?: string[];
};

const INDEX = cardsIndexJson as CardsIndex;
const LANG_KEYS = new Set<string>(PACK_LANGS);

export const LORCANA_CARDS_BASE = "/foil/lorcana/cards";

function entry(printKey: string | null | undefined): LorcanaCardPackEntry | null {
  if (!printKey) return null;
  return INDEX.cards[printKey] ?? INDEX.cards[printKey.toLowerCase()] ?? null;
}

function pickLangFiles(
  row: LorcanaCardPackEntry,
  preferred?: string | null,
): { language: string | null; files: LorcanaCardLangFiles } {
  const wanted = isPackLang(preferred) ? preferred : DEFAULT_PACK_LANG;
  const order: PackLang[] = [
    wanted,
    ...PACK_LANGS.filter((lang) => lang !== wanted),
  ];

  for (const lang of order) {
    const files = row[lang];
    if (files && (files.art || files.foilMask || files.thumb)) {
      return { language: lang, files };
    }
  }

  // Legacy scrape: files lived directly under {printKey}/.
  if (row.art || row.foilMask || row.thumb || row.varnishMask) {
    return { language: null, files: row };
  }
  return { language: null, files: {} };
}

function fileUrl(
  printKey: string,
  language: string | null,
  file: string | undefined,
): string | null {
  if (!file) return null;
  const segment = printKey
    .split("/")
    .map((part) => encodeURIComponent(part))
    .join("/");
  if (language && LANG_KEYS.has(language)) {
    return `${LORCANA_CARDS_BASE}/${segment}/${language}/${file}`;
  }
  return `${LORCANA_CARDS_BASE}/${segment}/${file}`;
}

export function packHasCard(printKey: string | null | undefined): boolean {
  const row = entry(printKey);
  if (!row) return false;
  const { files } = pickLangFiles(row);
  return Boolean(files.art || files.foilMask || files.thumb || files.varnishMask);
}

export function packFoilMaskUrl(
  printKey: string | null | undefined,
  language?: string | null,
): string | null {
  const row = entry(printKey);
  if (!row || !printKey) return null;
  const picked = pickLangFiles(row, language);
  return fileUrl(printKey, picked.language, picked.files.foilMask);
}

export function packVarnishMaskUrl(
  printKey: string | null | undefined,
  language?: string | null,
): string | null {
  const row = entry(printKey);
  if (!row || !printKey) return null;
  const picked = pickLangFiles(row, language);
  return fileUrl(printKey, picked.language, picked.files.varnishMask);
}

export function packSecondVarnishMaskUrl(
  printKey: string | null | undefined,
  language?: string | null,
): string | null {
  const row = entry(printKey);
  if (!row || !printKey) return null;
  const picked = pickLangFiles(row, language);
  return fileUrl(printKey, picked.language, picked.files.secondVarnishMask);
}

export function packArtUrl(
  printKey: string | null | undefined,
  language?: string | null,
): string | null {
  const row = entry(printKey);
  if (!row || !printKey) return null;
  const picked = pickLangFiles(row, language);
  return fileUrl(printKey, picked.language, picked.files.art);
}

export function packThumbUrl(
  printKey: string | null | undefined,
  language?: string | null,
): string | null {
  const row = entry(printKey);
  if (!row || !printKey) return null;
  const picked = pickLangFiles(row, language);
  return (
    fileUrl(printKey, picked.language, picked.files.thumb) ??
    fileUrl(printKey, picked.language, picked.files.art)
  );
}

/** Prefer pack URL when indexed; otherwise keep the remote / uploads URL. */
export function preferPackUrl(
  packUrl: string | null,
  fallback: string | null | undefined,
): string | null {
  return packUrl ?? fallback ?? null;
}

/** Swap catalogue remote URLs for pack paths when the scrape index has them. */
export function withPackCardUrls<
  T extends {
    printKey?: string | null;
    language?: string | null;
    imageUrl?: string | null;
    thumbnailUrl?: string | null;
    foilMaskUrl?: string | null;
    varnishMaskUrl?: string | null;
    secondVarnishMaskUrl?: string | null;
    variantImageUrls?: Record<string, string> | null;
  },
>(row: T): T {
  const printKey = row.printKey;
  if (!printKey || !packHasCard(printKey)) return row;
  const language = row.language;

  const art = packArtUrl(printKey, language);
  const thumb = packThumbUrl(printKey, language);
  const foil = packFoilMaskUrl(printKey, language);
  const varnish = packVarnishMaskUrl(printKey, language);
  const second = packSecondVarnishMaskUrl(printKey, language);

  const next: T = { ...row };
  if (art) {
    next.imageUrl = art as T["imageUrl"];
    if (row.variantImageUrls && Object.keys(row.variantImageUrls).length > 0) {
      next.variantImageUrls = Object.fromEntries(
        Object.keys(row.variantImageUrls).map((finish) => [finish, art]),
      ) as T["variantImageUrls"];
    }
  }
  if (thumb || art) {
    next.thumbnailUrl = (thumb ?? art) as T["thumbnailUrl"];
  }
  if (foil) next.foilMaskUrl = foil as T["foilMaskUrl"];
  if (varnish) next.varnishMaskUrl = varnish as T["varnishMaskUrl"];
  if (second) next.secondVarnishMaskUrl = second as T["secondVarnishMaskUrl"];
  return next;
}
