/**
 * Dragon Ball Heroes retail sealed — Extra / Ultimate / Big Bang / starters /
 * anniversary binder sets. Packshots from Amazon dig
 * (`curated/sources/amazon-packshots-2026-09-20.json`).
 */
import { existsSync } from "node:fs";
import path from "node:path";

import {
  writeLocalSealedProducts,
  type LocalSealedWrite,
} from "@/providers/shared/sealedProducts/localWrite";
import { installProviderProductsContents } from "@/providers/shared/sealedProducts/curatedContents";
import type { SealedKind } from "@/providers/shared/sealedProducts/kinds";

import { DBH_PACK_ID, dbhCuratedDir } from "./pack";

const SOURCE =
  "carddass / Amazon / Meccha / NipponTCG / Chitoroshop / toy-let / Rappcollect / Full Ahead packshots 2026-09-20";
const VERIFIED = "2026-09-20";

type DbhSealedSpec = {
  slug: string;
  kind: SealedKind;
  category: string;
  name: string;
  setCode: string;
  cardsPerPack: number | null;
  packsContained: number | null;
  declaredCardCount: number | null;
  path: string;
  artFile?: string;
};

/** Retail SKUs attested in curated/BACK.md + products-contents.json. */
const DBH_SEALED_SPECS: readonly DbhSealedSpec[] = [
  {
    slug: "extra-booster-pack-1",
    kind: "booster",
    category: "boosters",
    name: "SDBH Extra Booster Pack 1",
    setCode: "ebp1",
    cardsPerPack: 3,
    packsContained: 1,
    declaredCardCount: 40,
    path: "https://meccha-japan.com/fr/display/57938-extra-display-vol-01-super-dragon-ball-heroes-tcg.html",
    artFile: "extra-booster-pack-1.jpg",
  },
  {
    slug: "extra-booster-pack-1-box",
    kind: "display",
    category: "displays",
    name: "SDBH Extra Booster Pack 1 BOX (20)",
    setCode: "ebp1-box",
    cardsPerPack: null,
    packsContained: 20,
    declaredCardCount: null,
    path: "https://meccha-japan.com/fr/display/57938-extra-display-vol-01-super-dragon-ball-heroes-tcg.html",
    artFile: "extra-booster-pack-1-box.jpg",
  },
  {
    slug: "extra-booster-pack-2",
    kind: "booster",
    category: "boosters",
    name: "SDBH Extra Booster Pack 2",
    setCode: "ebp2",
    cardsPerPack: 3,
    packsContained: 1,
    declaredCardCount: 40,
    path: "https://www.nippontcg.fr/nos-displays/displays-japonais/super-dragon-ball-heroes-extra-booster-pack-2-pums12-display-japonais-scelle-booster-box-officielle",
    artFile: "extra-booster-pack-2.jpg",
  },
  {
    slug: "extra-booster-pack-2-box",
    kind: "display",
    category: "displays",
    name: "SDBH Extra Booster Pack 2 BOX (20) — PUMS12",
    setCode: "ebp2-box",
    cardsPerPack: null,
    packsContained: 20,
    declaredCardCount: null,
    path: "https://www.nippontcg.fr/nos-displays/displays-japonais/super-dragon-ball-heroes-extra-booster-pack-2-pums12-display-japonais-scelle-booster-box-officielle",
    artFile: "extra-booster-pack-2-box.jpg",
  },
  {
    slug: "extra-booster-pack-3",
    kind: "booster",
    category: "boosters",
    name: "SDBH Extra Booster Pack 3",
    setCode: "ebp3",
    cardsPerPack: 3,
    packsContained: 1,
    declaredCardCount: 40,
    path: "https://en.dragon-ball-official.com/news/01_2004.html",
    artFile: "extra-booster-pack-3.jpg",
  },
  {
    slug: "extra-booster-pack-3-box",
    kind: "display",
    category: "displays",
    name: "SDBH Extra Booster Pack 3 BOX (20)",
    setCode: "ebp3-box",
    cardsPerPack: null,
    packsContained: 20,
    declaredCardCount: null,
    path: "https://www.amazon.ca/-/fr/BANDAI-Dragon-Heroes-boosters-suppl%C3%A9mentaires/dp/B0C5593VG4",
    artFile: "extra-booster-pack-3-box.jpg",
  },
  {
    slug: "extra-booster-pack-4",
    kind: "booster",
    category: "boosters",
    name: "SDBH Extra Booster Pack 4",
    setCode: "ebp4",
    cardsPerPack: 3,
    packsContained: 1,
    declaredCardCount: 40,
    path: "https://www.carddass.com/dbh/sdbh_mm/products/extra_booster_4/",
    artFile: "extra-booster-pack-4.jpg",
  },
  {
    slug: "extra-booster-pack-4-box",
    kind: "display",
    category: "displays",
    name: "SDBH Extra Booster Pack 4 BOX (20)",
    setCode: "ebp4-box",
    cardsPerPack: null,
    packsContained: 20,
    declaredCardCount: null,
    path: "https://www.amazon.fr/Bandai-Dragon-Heroes-Booster-paquets/dp/B0CQY3LR45",
    artFile: "extra-booster-pack-4-box.jpg",
  },
  {
    slug: "extra-booster-pack-box",
    kind: "display",
    category: "displays",
    name: "SDBH Extra Booster Pack BOX (20)",
    setCode: "ebp-box",
    cardsPerPack: null,
    packsContained: 20,
    declaredCardCount: null,
    path: "retail BOX Extra Booster Pack (20 packs × 3) — generic; prefer ebpN-box when set known",
  },
  {
    slug: "booster-selection-pack",
    kind: "booster",
    category: "boosters",
    name: "SDBH Selection Pack Vol.1 (SP01)",
    setCode: "sp01",
    cardsPerPack: 3,
    packsContained: 1,
    declaredCardCount: null,
    path: "https://toy-let.com/products/sdbh-selection-pack-vol-1",
    artFile: "toy-let/selection-pack-vol-1.png",
  },
  {
    slug: "booster-selection-pack-box",
    kind: "display",
    category: "displays",
    name: "SDBH Selection Pack Vol.1 BOX (20) — SP01",
    setCode: "sp01-box",
    cardsPerPack: null,
    packsContained: 20,
    declaredCardCount: null,
    path: "https://toy-let.com/products/sdbh-selection-pack-vol-1",
    artFile: "toy-let/selection-pack-vol-1-box.png",
  },
  {
    slug: "booster-selection-pack-vol-2",
    kind: "booster",
    category: "boosters",
    name: "SDBH Selection Pack Vol.2 (SP02)",
    setCode: "sp02",
    cardsPerPack: 3,
    packsContained: 1,
    declaredCardCount: null,
    path: "https://toy-let.com/products/sdh-selection-pack-vol-2",
    artFile: "toy-let/selection-pack-vol-2.png",
  },
  {
    slug: "booster-selection-pack-vol-2-box",
    kind: "display",
    category: "displays",
    name: "SDBH Selection Pack Vol.2 BOX (20) — SP02",
    setCode: "sp02-box",
    cardsPerPack: null,
    packsContained: 20,
    declaredCardCount: null,
    path: "https://toy-let.com/products/sdh-selection-pack-vol-2",
    artFile: "toy-let/selection-pack-vol-2-box.png",
  },
  {
    slug: "booster-selection-pack-vol-3",
    kind: "booster",
    category: "boosters",
    name: "SDBH Selection Pack Vol.3 (SP03)",
    setCode: "sp03",
    cardsPerPack: 3,
    packsContained: 1,
    declaredCardCount: null,
    path: "https://toy-let.com/products/sdbh-selection-pack-vol-3",
    artFile: "toy-let/selection-pack-vol-3.png",
  },
  {
    slug: "booster-selection-pack-vol-3-box",
    kind: "display",
    category: "displays",
    name: "SDBH Selection Pack Vol.3 BOX (20) — SP03",
    setCode: "sp03-box",
    cardsPerPack: null,
    packsContained: 20,
    declaredCardCount: null,
    path: "https://toy-let.com/products/sdbh-selection-pack-vol-3",
    artFile: "toy-let/selection-pack-vol-3-box.png",
  },
  {
    slug: "ultimate-booster-bravery",
    kind: "booster",
    category: "boosters",
    name: "SDBH Ultimate Booster — Bravery Clash",
    setCode: "ub-bravery",
    cardsPerPack: 3,
    packsContained: 1,
    declaredCardCount: 30,
    path: "https://sec.carddass.com/club/products/detail/4549660401124000",
    artFile: "ultimate-booster-bravery.jpg",
  },
  {
    slug: "ultimate-booster-bravery-box",
    kind: "display",
    category: "displays",
    name: "SDBH Ultimate Booster — Bravery Clash BOX",
    setCode: "ub-bravery-box",
    cardsPerPack: null,
    packsContained: 20,
    declaredCardCount: null,
    path: "https://sec.carddass.com/club/products/detail/4549660401124000",
    artFile: "ultimate-booster-bravery-box.jpg",
  },
  {
    slug: "ultimate-booster-power-breakthrough",
    kind: "booster",
    category: "boosters",
    name: "SDBH Ultimate Booster — Power Breakthrough",
    setCode: "ub-power",
    cardsPerPack: 3,
    packsContained: 1,
    declaredCardCount: 30,
    path: "https://sec.carddass.com/club/products/detail/4549660364870000",
    artFile: "ultimate-booster-power-breakthrough.jpg",
  },
  {
    slug: "ultimate-booster-power-breakthrough-box",
    kind: "display",
    category: "displays",
    name: "SDBH Ultimate Booster — Power Breakthrough BOX",
    setCode: "ub-power-box",
    cardsPerPack: null,
    packsContained: 20,
    declaredCardCount: null,
    path: "https://sec.carddass.com/club/products/detail/4549660364870000",
    artFile: "ultimate-booster-power-breakthrough-box.jpg",
  },
  {
    slug: "ultimate-booster-new-clash",
    kind: "booster",
    category: "boosters",
    name: "SDBH Ultimate Booster — New Fierce Battle",
    setCode: "ub-new-clash",
    cardsPerPack: 3,
    packsContained: 1,
    declaredCardCount: 30,
    path: "https://pt-fullahead.com/shopdetail/000000050213/",
    artFile: "fullahead/ultimate-booster-new-clash.jpg",
  },
  {
    slug: "ultimate-booster-new-clash-box",
    kind: "display",
    category: "displays",
    name: "SDBH Ultimate Booster — New Fierce Battle BOX",
    setCode: "ub-new-clash-box",
    cardsPerPack: null,
    packsContained: 20,
    declaredCardCount: null,
    path: "https://pt-fullahead.com/shopdetail/000000050128/",
    // Full Ahead BOX listing still shows pack face only — leave image null.
  },
  {
    slug: "ultimate-booster-super-warrior",
    kind: "booster",
    category: "boosters",
    name: "SDBH Ultimate Booster — Super Warrior Gathering",
    setCode: "ub-super-warrior",
    cardsPerPack: 3,
    packsContained: 1,
    declaredCardCount: 30,
    path: "https://pt-fullahead.com/shopdetail/000000050216/",
    artFile: "fullahead/ultimate-booster-super-warrior.jpg",
  },
  {
    slug: "ultimate-booster-super-warrior-box",
    kind: "display",
    category: "displays",
    name: "SDBH Ultimate Booster — Super Warrior Gathering BOX",
    setCode: "ub-super-warrior-box",
    cardsPerPack: null,
    packsContained: 20,
    declaredCardCount: null,
    path: "https://pt-fullahead.com/shopdetail/000000050129/",
    artFile: "fullahead/ultimate-booster-super-warrior-box.jpg",
  },
  {
    slug: "ultimate-booster-dbh",
    kind: "booster",
    category: "boosters",
    name: "DBH Ultimate Booster Pack (HUM)",
    setCode: "ub-dbh",
    cardsPerPack: 3,
    packsContained: 1,
    declaredCardCount: 30,
    path: "https://pt-fullahead.com/shopdetail/000000050141/",
    artFile: "fullahead/ultimate-booster-dbh.jpg",
  },
  {
    slug: "big-bang-booster-pack-1",
    kind: "booster",
    category: "boosters",
    name: "SDBH Big Bang Mission Vol.1 (BMT1)",
    setCode: "bmt1",
    cardsPerPack: 3,
    packsContained: 1,
    declaredCardCount: 100,
    path: "https://rappcollect.com/products/super-dragon-ball-heroes-big-bang-mission-1-booster-box",
    artFile: "rappcollect/big-bang-mission-ver-1.jpg",
  },
  {
    slug: "big-bang-booster-pack-1-box",
    kind: "display",
    category: "displays",
    name: "SDBH Big Bang Mission Vol.1 BOX (20) — BMT1",
    setCode: "bmt1-box",
    cardsPerPack: null,
    packsContained: 20,
    declaredCardCount: null,
    path: "https://rappcollect.com/products/super-dragon-ball-heroes-big-bang-mission-1-booster-box",
    artFile: "rappcollect/big-bang-mission-ver-1-box.jpg",
  },
  {
    slug: "big-bang-booster-pack-2",
    kind: "booster",
    category: "boosters",
    name: "SDBH Big Bang Mission Vol.2 (BMT2)",
    setCode: "bmt2",
    cardsPerPack: 3,
    packsContained: 1,
    declaredCardCount: 86,
    path: "https://rappcollect.com/products/super-dragon-ball-heroes-big-bang-mission-2-booster-box",
    artFile: "rappcollect/big-bang-mission-ver-2.jpg",
  },
  {
    slug: "big-bang-booster-pack-2-box",
    kind: "display",
    category: "displays",
    name: "SDBH Big Bang Mission Vol.2 BOX (20) — BMT2",
    setCode: "bmt2-box",
    cardsPerPack: null,
    packsContained: 20,
    declaredCardCount: null,
    path: "https://rappcollect.com/products/super-dragon-ball-heroes-big-bang-mission-2-booster-box",
    artFile: "rappcollect/big-bang-mission-ver-2-box.jpg",
  },
  {
    slug: "big-bang-booster-pack-3",
    kind: "booster",
    category: "boosters",
    name: "SDBH Big Bang Mission Vol.3 (BMT3)",
    setCode: "bmt3",
    cardsPerPack: 3,
    packsContained: 1,
    declaredCardCount: null,
    path: "https://toy-let.com/products/sdbhe-big-bang-mission-ver-3",
    artFile: "toy-let/big-bang-mission-ver-3.png",
  },
  {
    slug: "big-bang-booster-pack-3-box",
    kind: "display",
    category: "displays",
    name: "SDBH Big Bang Mission Vol.3 BOX (20) — BMT3",
    setCode: "bmt3-box",
    cardsPerPack: null,
    packsContained: 20,
    declaredCardCount: null,
    path: "https://toy-let.com/products/sdbhe-big-bang-mission-ver-3",
    artFile: "toy-let/big-bang-mission-ver-3-box.png",
  },
  {
    slug: "big-bang-booster-pack-4",
    kind: "booster",
    category: "boosters",
    name: "SDBH Big Bang Mission Vol.4 (BMT4)",
    setCode: "bmt4",
    cardsPerPack: 3,
    packsContained: 1,
    declaredCardCount: null,
    path: "https://toy-let.com/products/sdbh-big-bang-mission-ver-4",
    artFile: "toy-let/big-bang-mission-ver-4.png",
  },
  {
    slug: "big-bang-booster-pack-4-box",
    kind: "display",
    category: "displays",
    name: "SDBH Big Bang Mission Vol.4 BOX (20) — BMT4",
    setCode: "bmt4-box",
    cardsPerPack: null,
    packsContained: 20,
    declaredCardCount: null,
    path: "https://toy-let.com/products/sdbh-big-bang-mission-ver-4",
    artFile: "toy-let/big-bang-mission-ver-4-box.png",
  },
  {
    slug: "big-bang-booster-pack-5",
    kind: "booster",
    category: "boosters",
    name: "SDBH Big Bang Mission Vol.5 (BMT5)",
    setCode: "bmt5",
    cardsPerPack: 3,
    packsContained: 1,
    declaredCardCount: null,
    path: "https://toy-let.com/products/super-dragonball-heroes-big-bang-mission-ver-5-hk",
    artFile: "toy-let/big-bang-mission-ver-5.png",
  },
  {
    slug: "big-bang-booster-pack-5-box",
    kind: "display",
    category: "displays",
    name: "SDBH Big Bang Mission Vol.5 BOX (20) — BMT5",
    setCode: "bmt5-box",
    cardsPerPack: null,
    packsContained: 20,
    declaredCardCount: null,
    path: "https://rappcollect.com/products/super-dragon-ball-heroes-big-bang-mission-ver-5-booster-box-20-packs",
    artFile: "rappcollect/big-bang-mission-ver-5-box.jpg",
  },
  {
    slug: "big-bang-booster-pack-6",
    kind: "booster",
    category: "boosters",
    name: "SDBH Big Bang Mission Vol.6 (BMT6)",
    setCode: "bmt6",
    cardsPerPack: 3,
    packsContained: 1,
    declaredCardCount: null,
    path: "https://toy-let.com/products/super-dragonball-heroes-big-bang-mission-ver-6-hk",
    artFile: "toy-let/big-bang-mission-ver-6.png",
  },
  {
    slug: "big-bang-booster-pack-6-box",
    kind: "display",
    category: "displays",
    name: "SDBH Big Bang Mission Vol.6 BOX (20) — BMT6",
    setCode: "bmt6-box",
    cardsPerPack: null,
    packsContained: 20,
    declaredCardCount: null,
    path: "https://toy-let.com/products/super-dragonball-heroes-big-bang-mission-ver-6-hk",
  },
  {
    slug: "big-bang-booster-pack-7",
    kind: "booster",
    category: "boosters",
    name: "SDBH Big Bang Mission Vol.7 (BMT7)",
    setCode: "bmt7",
    cardsPerPack: 3,
    packsContained: 1,
    declaredCardCount: null,
    path: "https://toy-let.com/products/super-dragonball-heroes-sdhb-big-bang-mission-ver-7",
    artFile: "toy-let/big-bang-mission-ver-7.jpg",
  },
  {
    slug: "big-bang-booster-pack-7-box",
    kind: "display",
    category: "displays",
    name: "SDBH Big Bang Mission Vol.7 BOX (20) — BMT7",
    setCode: "bmt7-box",
    cardsPerPack: null,
    packsContained: 20,
    declaredCardCount: null,
    path: "https://toy-let.com/products/super-dragonball-heroes-sdhb-big-bang-mission-ver-7",
    artFile: "toy-let/big-bang-mission-ver-7-box.jpg",
  },
  {
    slug: "big-bang-booster-pack-8",
    kind: "booster",
    category: "boosters",
    name: "SDBH Big Bang Mission Vol.8 (BMT8)",
    setCode: "bmt8",
    cardsPerPack: 3,
    packsContained: 1,
    declaredCardCount: 87,
    path: "https://rappcollect.com/products/super-dragon-ball-heroes-big-bang-mission-ver-8-booster-box-20-packs",
    artFile: "rappcollect/big-bang-mission-ver-8.jpg",
  },
  {
    slug: "big-bang-booster-pack-8-box",
    kind: "display",
    category: "displays",
    name: "SDBH Big Bang Mission Vol.8 BOX (20) — BMT8",
    setCode: "bmt8-box",
    cardsPerPack: null,
    packsContained: 20,
    declaredCardCount: null,
    path: "https://rappcollect.com/products/super-dragon-ball-heroes-big-bang-mission-ver-8-booster-box-20-packs",
    artFile: "rappcollect/big-bang-mission-ver-8-box.jpg",
  },
  {
    slug: "big-bang-booster-pack-9",
    kind: "booster",
    category: "boosters",
    name: "SDBH Big Bang Mission Vol.9 (BMT9)",
    setCode: "bmt9",
    cardsPerPack: 3,
    packsContained: 1,
    declaredCardCount: 85,
    path: "https://toy-let.com/products/super-dragonball-heroes-sdbh-big-bang-mission-ver-9",
    artFile: "toy-let/big-bang-mission-ver-9.jpg",
  },
  {
    slug: "big-bang-booster-pack-9-box",
    kind: "display",
    category: "displays",
    name: "SDBH Big Bang Mission Vol.9 BOX (20) — BMT9",
    setCode: "bmt9-box",
    cardsPerPack: null,
    packsContained: 20,
    declaredCardCount: null,
    path: "https://rappcollect.com/products/super-dragon-ball-heroes-big-bang-mission-ver-9-booster-box-20-packs",
    artFile: "rappcollect/big-bang-mission-ver-9-box.jpg",
  },
  {
    slug: "big-bang-booster-pack-10",
    kind: "booster",
    category: "boosters",
    name: "SDBH Big Bang Mission Vol.10 (BMT10)",
    setCode: "bmt10",
    cardsPerPack: 3,
    packsContained: 1,
    declaredCardCount: null,
    path: "https://toy-let.com/products/super-dragonball-heroes-sdbh-big-bang-mission-ver-10",
    artFile: "toy-let/big-bang-mission-ver-10.jpg",
  },
  {
    slug: "big-bang-booster-pack-10-box",
    kind: "display",
    category: "displays",
    name: "SDBH Big Bang Mission Vol.10 BOX (20) — BMT10",
    setCode: "bmt10-box",
    cardsPerPack: null,
    packsContained: 20,
    declaredCardCount: null,
    path: "https://toy-let.com/products/super-dragonball-heroes-sdbh-big-bang-mission-ver-10",
    artFile: "toy-let/big-bang-mission-ver-10-box.jpg",
  },
  {
    slug: "big-bang-booster-pack-11",
    kind: "booster",
    category: "boosters",
    name: "SDBH Big Bang Mission Vol.11 (BMT11)",
    setCode: "bmt11",
    cardsPerPack: 3,
    packsContained: 1,
    declaredCardCount: 94,
    path: "https://toy-let.com/products/super-dragonball-heroes-sdbh-big-bang-mission-ver-11",
    artFile: "toy-let/big-bang-mission-ver-11.png",
  },
  {
    slug: "big-bang-booster-pack-11-box",
    kind: "display",
    category: "displays",
    name: "SDBH Big Bang Mission Vol.11 BOX (20) — BMT11",
    setCode: "bmt11-box",
    cardsPerPack: null,
    packsContained: 20,
    declaredCardCount: null,
    path: "https://toy-let.com/products/super-dragonball-heroes-sdbh-big-bang-mission-ver-11",
    artFile: "toy-let/big-bang-mission-ver-11-box.png",
  },
  {
    slug: "big-bang-booster-pack-12",
    kind: "booster",
    category: "boosters",
    name: "SDBH Big Bang Mission Vol.12 (BMT12)",
    setCode: "bmt12",
    cardsPerPack: 3,
    packsContained: 1,
    declaredCardCount: null,
    path: "https://toy-let.com/products/super-dragonball-heroes-sdbh-big-bang-mission-ver-12",
    artFile: "toy-let/big-bang-mission-ver-12.jpg",
  },
  {
    slug: "big-bang-booster-pack-12-box",
    kind: "display",
    category: "displays",
    name: "SDBH Big Bang Mission Vol.12 BOX (20) — BMT12",
    setCode: "bmt12-box",
    cardsPerPack: null,
    packsContained: 20,
    declaredCardCount: null,
    path: "https://toy-let.com/products/super-dragonball-heroes-sdbh-big-bang-mission-ver-12",
    artFile: "toy-let/big-bang-mission-ver-12-box.png",
  },
  {
    slug: "evolution-pack-vol-1",
    kind: "booster",
    category: "boosters",
    name: "SDBH Evolution Pack Vol.1 (EVT1)",
    setCode: "evt1",
    cardsPerPack: null,
    packsContained: 1,
    declaredCardCount: null,
    path: "https://toy-let.com/products/sdbh-evolution-pack-vol-1",
    artFile: "toy-let/evolution-pack-vol-1.jpg",
  },
  {
    slug: "evolution-pack-vol-1-box",
    kind: "display",
    category: "displays",
    name: "SDBH Evolution Pack Vol.1 BOX (20) — EVT1",
    setCode: "evt1-box",
    cardsPerPack: null,
    packsContained: 20,
    declaredCardCount: null,
    path: "https://toy-let.com/products/sdbh-evolution-pack-vol-1",
    artFile: "toy-let/evolution-pack-vol-1-box.png",
  },
  {
    slug: "evolution-pack-vol-3",
    kind: "booster",
    category: "boosters",
    name: "SDBH Evolution Pack Vol.3 (EVT3)",
    setCode: "evt3",
    cardsPerPack: null,
    packsContained: 1,
    declaredCardCount: null,
    path: "https://toy-let.com/products/sdbh-evolution-pack-vol-3",
    artFile: "toy-let/evolution-pack-vol-3.jpg",
  },
  {
    slug: "evolution-pack-vol-3-box",
    kind: "display",
    category: "displays",
    name: "SDBH Evolution Pack Vol.3 BOX (20) — EVT3",
    setCode: "evt3-box",
    cardsPerPack: null,
    packsContained: 20,
    declaredCardCount: null,
    path: "https://toy-let.com/products/sdbh-evolution-pack-vol-3",
    artFile: "toy-let/evolution-pack-vol-3.jpg",
  },
  {
    slug: "bigbang-star-2-box",
    kind: "display",
    category: "displays",
    name: "SDBH Bigbang Star 2 Booster BOX",
    setCode: "bbs2-box",
    cardsPerPack: null,
    packsContained: 20,
    declaredCardCount: null,
    path: "https://chitoroshop.com/products/super-dragon-ball-heroes-bigbang-star-2-booster-box",
    artFile:
      "chitoroshop/super-dragon-ball-heroes-bigbang-star-2-booster-box-1.png",
  },
  {
    slug: "super-warrior-gathering-box",
    kind: "display",
    category: "displays",
    name: "SDBH Super Warrior Gathering Booster BOX",
    setCode: "swg-box",
    cardsPerPack: null,
    packsContained: 20,
    declaredCardCount: null,
    path: "https://chitoroshop.com/products/super-dragon-ball-heroes-super-warrior-gathering-booster-box",
    artFile:
      "chitoroshop/super-dragon-ball-heroes-super-warrior-gathering-booster-box-1.png",
  },
  {
    slug: "pums3-pack",
    kind: "booster",
    category: "boosters",
    name: "SDBH Premium Special Pack PUMS3",
    setCode: "pums3",
    cardsPerPack: null,
    packsContained: 1,
    declaredCardCount: null,
    path: "https://chitoroshop.com/products/super-dragon-ball-heores-pums3-pack",
    artFile: "chitoroshop/super-dragon-ball-heores-pums3-pack-1.jpg",
  },
  {
    slug: "pums4-pack",
    kind: "booster",
    category: "boosters",
    name: "SDBH Premium Special Pack PUMS4",
    setCode: "pums4",
    cardsPerPack: null,
    packsContained: 1,
    declaredCardCount: null,
    path: "https://chitoroshop.com/products/super-dragon-ball-heores-pums4-pack",
    artFile: "chitoroshop/super-dragon-ball-heores-pums4-pack-1.jpg",
  },
  {
    slug: "pums6-pack",
    kind: "booster",
    category: "boosters",
    name: "SDBH Premium Special Pack PUMS6",
    setCode: "pums6",
    cardsPerPack: null,
    packsContained: 1,
    declaredCardCount: null,
    path: "https://chitoroshop.com/products/super-dragon-ball-heores-pums6-pack",
    artFile: "chitoroshop/super-dragon-ball-heores-pums6-pack-1.jpg",
  },
  {
    slug: "pums13-pack",
    kind: "booster",
    category: "boosters",
    name: "SDBH Premium Special Pack PUMS13",
    setCode: "pums13",
    cardsPerPack: null,
    packsContained: 1,
    declaredCardCount: null,
    path: "https://chitoroshop.com/products/super-dragon-ball-heores-pums13-pack",
    artFile: "chitoroshop/super-dragon-ball-heores-pums13-pack-1.jpg",
  },
  {
    slug: "pums14-pack",
    kind: "booster",
    category: "boosters",
    name: "SDBH Premium Special Pack PUMS14",
    setCode: "pums14",
    cardsPerPack: null,
    packsContained: 1,
    declaredCardCount: null,
    path: "https://chitoroshop.com/products/super-dragon-ball-heores-pums14-pack",
    artFile: "chitoroshop/super-dragon-ball-heores-pums14-pack-1.jpg",
  },
  {
    slug: "starter-pack-namek-battle",
    kind: "deck",
    category: "starter-deck",
    name: "SDBH Starter Pack — Namek Battle",
    setCode: "ugmps",
    cardsPerPack: null,
    packsContained: 1,
    declaredCardCount: 7,
    path: "https://www.amazon.ca/-/fr/Bandai-Dragon-Heroes-Starter-Battle/dp/B0BS8ML1D1",
    artFile: "starter-pack-namek-battle.jpg",
  },
  {
    slug: "starter-pack-burst",
    kind: "deck",
    category: "starter-deck",
    name: "SDBH Starter Pack — Burst",
    setCode: "bmps",
    cardsPerPack: null,
    packsContained: 1,
    declaredCardCount: 7,
    path: "https://www.amazon.ca/-/fr/Bandai-Super-Dragon-Heroes-Starter/dp/B09B22PVT9",
    artFile: "starter-pack-burst.jpg",
  },
  {
    slug: "starter-pack-ultimate-silver",
    kind: "deck",
    category: "starter-deck",
    name: "SDBH Starter Pack — Ultimate Silver",
    setCode: "bmps-silver",
    cardsPerPack: null,
    packsContained: 1,
    declaredCardCount: 7,
    path: "https://sec.carddass.com/club/products/detail/4549660505686000",
    artFile: "carddass/starter-pack-ultimate-silver.jpg",
  },
  {
    slug: "starter-pack-xeno-gold",
    kind: "deck",
    category: "starter-deck",
    name: "SDBH Starter Pack — Xeno Gold",
    setCode: "bmps-gold",
    cardsPerPack: null,
    packsContained: 1,
    declaredCardCount: 7,
    path: "https://sec.carddass.com/club/products/detail/4549660505693000",
    artFile: "carddass/starter-pack-xeno-gold.jpg",
  },
  {
    slug: "binder-12th-anniversary-ultra-god",
    kind: "collector_box",
    category: "collector-boxes",
    name: "SDBH Official 9-Pocket Binder — 12th Anniversary Ultra God Mission Set",
    setCode: "binder-12th",
    cardsPerPack: null,
    packsContained: 1,
    declaredCardCount: 14,
    path: "https://www.amazon.ca/-/fr/BANDAI-Classeur-officiel-pochettes-anniversaire/dp/B0B8RDYXHG",
    artFile: "binder-12th-anniversary-ultra-god.jpg",
  },
  {
    slug: "binder-13th-anniversary-cell",
    kind: "collector_box",
    category: "collector-boxes",
    name: "SDBH Official 9-Pocket Binder — 13th Anniversary Cell Arc Set",
    setCode: "binder-13th",
    cardsPerPack: null,
    packsContained: 1,
    declaredCardCount: 14,
    path: "https://www.amazon.co.jp/-/en/dp/B0CFLBGK35",
    artFile: "binder-13th-anniversary-cell.jpg",
  },
];

function curatedProductArt(name: string): string | null {
  const p = path.join(dbhCuratedDir(), "products", name);
  return existsSync(p) ? p : null;
}

export function ingestDbhSealedProducts(): {
  pack: string;
  written: number;
  skipped: number;
  file: string;
} {
  installProviderProductsContents(
    DBH_PACK_ID,
    path.join(dbhCuratedDir(), "products-contents.json"),
  );

  const products: LocalSealedWrite[] = DBH_SEALED_SPECS.map((spec) => ({
    slug: spec.slug,
    kind: spec.kind,
    category: spec.category,
    name: spec.name,
    source: "carddass-dbh",
    setCode: spec.setCode,
    catalogueSetId: spec.setCode,
    lang: "ja",
    releaseDate: null,
    declaredCardCount: spec.declaredCardCount,
    cardsPerPack: spec.cardsPerPack,
    packsContained: spec.packsContained,
    path: spec.path,
    artPath: spec.artFile ? curatedProductArt(spec.artFile) : null,
  }));

  return writeLocalSealedProducts({
    packId: DBH_PACK_ID,
    source: "carddass-dbh",
    products,
    allowMissingArt: true,
  });
}

export const DBH_SEALED_SOURCE = SOURCE;
export const DBH_SEALED_VERIFIED = VERIFIED;
