// Static provider platform snapshots fetched on 2026-06-22.
// Sources:
// - ScreenScraper api2/systemesListe.php (names only, media URLs intentionally omitted)
// - LaunchBox Games Database public platform select
// These are build-time data for aliases/audits; the app must not fetch them live.

export type ScreenScraperPlatformReference = {
  id: number;
  type: string;
  names: readonly string[];
};

export type LaunchBoxPlatformReference = {
  id: number;
  name: string;
};

export const SCREEN_SCRAPER_PLATFORM_REFERENCES = [
  {
    id: 1,
    type: "Console",
    names: [
      "genesis",
      "Genesis",
      "megadrive",
      "Megadrive",
      "Sega Genesis",
      "Sega Megadrive",
      "Super Aladdin Boy",
    ],
  },
  {
    id: 2,
    type: "Console",
    names: [
      "Master System",
      "mastersystem",
      "Sega Mark 3",
      "Sega Mark III",
      "Sega Master System",
      "SMS",
    ],
  },
  {
    id: 3,
    type: "Console",
    names: [
      "Famicom",
      "Family Computer",
      "nes",
      "NES",
      "Nintendo Entertainment System",
      "Nintendo Famicom",
      "Nintendo Family Computer",
    ],
  },
  {
    id: 4,
    type: "Console",
    names: [
      "Nintendo super Famicom",
      "Nintendo Super Famicom",
      "snes",
      "SNES",
      "Super Famicom",
      "Super Nintendo",
      "Super Nintendo Entertainment System",
    ],
  },
  {
    id: 6,
    type: "Arcade",
    names: [
      "arcade",
      "Capcom Play System",
      "Capcom Play System 1",
      "Capcom Play System I",
      "CPS 1",
      "CPS I",
      "fba",
      "fba_libretro",
      "mame",
      "mame-advmame",
      "mame-libretro",
      "mame-mame4all",
      "mess",
    ],
  },
  {
    id: 7,
    type: "Arcade",
    names: [
      "arcade",
      "Capcom Play System 2",
      "Capcom Play System II",
      "CPS 2",
      "CPS II",
      "fba",
      "fba_libretro",
      "mame",
      "mame-advmame",
      "mame-libretro",
      "mame-mame4all",
      "mess",
    ],
  },
  {
    id: 8,
    type: "Arcade",
    names: [
      "arcade",
      "Capcom Play System 3",
      "Capcom Play System III",
      "CPS 3",
      "CPS III",
      "fba",
      "fba_libretro",
      "mame",
      "mame-advmame",
      "mame-libretro",
      "mame-mame4all",
      "mess",
    ],
  },
  {
    id: 9,
    type: "Console Portable",
    names: ["Game Boy", "gb", "GB", "Nintendo Game Boy", "Nintendo GB"],
  },
  {
    id: 10,
    type: "Console Portable",
    names: [
      "Game Boy Color",
      "GB Color",
      "gbc",
      "GBC",
      "Nintendo Game Boy Color",
      "Nintendo GB Color",
      "Nintendo GBC",
    ],
  },
  {
    id: 11,
    type: "Console Portable",
    names: [
      "Nintendo vboy",
      "Nintendo Virtual Boy",
      "Nintendo virtualboy",
      "vboy",
      "Virtual Boy",
      "virtualboy",
    ],
  },
  {
    id: 12,
    type: "Console Portable",
    names: [
      "Game Boy Advance",
      "GameBoy Advance",
      "GB Advance",
      "gba",
      "GBA",
      "Nintendo Game Boy Advance",
      "Nintendo GameBoy Advance",
      "Nintendo GB Advance",
      "Nintendo GBA",
    ],
  },
  {
    id: 13,
    type: "Console",
    names: [
      "Game Cube",
      "Gamecube",
      "gc",
      "GC",
      "NGC",
      "Nintendo Game Cube",
      "Nintendo GameCube",
      "Nintendo GC",
    ],
  },
  {
    id: 14,
    type: "Console",
    names: ["n64", "Nintendo 64"],
  },
  {
    id: 15,
    type: "Console Portable",
    names: ["DS", "DSi", "nds", "NDS", "NDSi", "Nintendo DS", "Nintendo DSi"],
  },
  {
    id: 16,
    type: "Console",
    names: ["Nintendo Wii", "Nintendo WII", "wii", "Wii", "WII"],
  },
  {
    id: 17,
    type: "Console Portable",
    names: ["2DS", "3DS", "Nintendo 3DS"],
  },
  {
    id: 18,
    type: "Console",
    names: ["Nintendo Wii U", "Nintendo WII-U", "Wii U", "WII-U", "wiiu"],
  },
  {
    id: 19,
    type: "Console",
    names: [
      "32x",
      "Genesis 32x",
      "Megadrive 32x",
      "Megadrive 32X",
      "Sega 32x",
      "Sega 32X",
      "Sega Genesis 32x",
      "Sega Mega 32x",
      "Sega Megadrive 32x",
      "sega32x",
      "Super 32x",
    ],
  },
  {
    id: 20,
    type: "Console",
    names: ["Mega-CD", "Sega CD", "segacd"],
  },
  {
    id: 21,
    type: "Console Portable",
    names: ["Game Gear", "gamegear", "GG", "Sega Game Gear", "Sega GG"],
  },
  {
    id: 22,
    type: "Console",
    names: ["saturn", "Saturn", "Sega Saturn"],
  },
  {
    id: 23,
    type: "Console",
    names: ["DC", "dreamcast", "Dreamcast", "Sega DC", "Sega Dreamcast"],
  },
  {
    id: 25,
    type: "Console Portable",
    names: [
      "GP",
      "Neo-Geo Pocket",
      "ngp",
      "SNK Neo Geo Pocket",
      "SNK Neo-Geo Pocket",
      "SNK NGP",
    ],
  },
  {
    id: 26,
    type: "Console",
    names: ["2600", "A2600", "Atari 2600", "atari2600", "Atari2600"],
  },
  {
    id: 27,
    type: "Console",
    names: ["Atari Jaguar", "atarijaguar", "jaguar", "Jaguar"],
  },
  {
    id: 28,
    type: "Console Portable",
    names: ["Atari Lynx", "atarilynx", "lynx", "Lynx"],
  },
  {
    id: 29,
    type: "Console",
    names: [
      "3do",
      "3DO",
      "3DO Interactive Multiplayer",
      "Panasonic 3DO",
      "Panasonic 3DO Interactive Multiplayer",
    ],
  },
  {
    id: 30,
    type: "Console Portable",
    names: ["N-Gage", "ngage", "Nokia N-Gage"],
  },
  {
    id: 31,
    type: "Console",
    names: [
      "NEC PC Engine",
      "NEC TurboGrafx-16",
      "PC Engine",
      "pcengine",
      "tg16",
      "TurboGrafx-16",
    ],
  },
  {
    id: 32,
    type: "Console",
    names: ["Microsoft Xbox", "Microsoft XBOX", "xbox", "Xbox", "XBOX"],
  },
  {
    id: 33,
    type: "Console",
    names: ["Microsoft Xbox 360", "Microsoft XBOX 360", "Xbox 360", "XBOX 360"],
  },
  {
    id: 34,
    type: "Console",
    names: ["Microsoft Xbox One", "Microsoft XBOX One", "Xbox One", "XBOX One"],
  },
  {
    id: 36,
    type: "Ordinateur",
    names: ["Acorn Atom", "Acorn ATOM", "Atom", "ATOM"],
  },
  {
    id: 37,
    type: "Ordinateur",
    names: [
      "Acorn BBC Micro",
      "Acorn BBC Microcomputer System",
      "BBC Micro",
      "BBC Microcomputer System",
      "bbcmicro",
    ],
  },
  {
    id: 39,
    type: "Accessoire",
    names: [
      "2600 SC",
      "2600 Supercharger",
      "A2600 SC",
      "A2600 Supercharger",
      "Atari 2600 SC",
      "Atari 2600 Supercharger",
    ],
  },
  {
    id: 40,
    type: "Console",
    names: ["5200", "A5200", "Atari 5200", "atari5200"],
  },
  {
    id: 41,
    type: "Console",
    names: ["7800", "A7800", "Atari 7800", "atari7800"],
  },
  {
    id: 42,
    type: "Ordinateur",
    names: [
      "1040 ST",
      "520 ST",
      "Atari 1040 ST",
      "Atari 520 ST",
      "Atari ST",
      "Atari STE",
      "atarist",
    ],
  },
  {
    id: 43,
    type: "Ordinateur",
    names: [
      "1200XL",
      "130XE",
      "600XL",
      "65XE",
      "800XE",
      "800XL",
      "A400",
      "A800",
      "Atari 1200XL",
      "Atari 130XE",
      "Atari 400",
      "Atari 600XL",
      "Atari 65XE",
      "Atari 8-Bit",
      "Atari 800",
      "Atari 800XE",
      "Atari 800XL",
      "Atari 8bit",
      "Atari XEGS",
      "atari800",
      "XEGS",
    ],
  },
  {
    id: 44,
    type: "Console",
    names: ["astrocade", "Astrocade", "Bally Astrocade"],
  },
  {
    id: 45,
    type: "Console Portable",
    names: [
      "Bandai WonderSwan",
      "Bandai WSwan",
      "wonderswan",
      "WonderSwan",
      "WSwan",
    ],
  },
  {
    id: 46,
    type: "Console Portable",
    names: [
      "Bandai WonderSwan Color",
      "Bandai WSwan Color",
      "WonderSwan Color",
      "wonderswancolor",
      "WSwan Color",
    ],
  },
  {
    id: 47,
    type: "Arcade",
    names: [
      "arcade",
      "Cave",
      "fba",
      "fba_libretro",
      "mame",
      "mame-advmame",
      "mame-libretro",
      "mame-mame4all",
      "mess",
    ],
  },
  {
    id: 48,
    type: "Console",
    names: ["colecovision", "Colecovision", "ColecoVision"],
  },
  {
    id: 49,
    type: "Emulation Arcade",
    names: [
      "arcade",
      "daphne",
      "Daphne",
      "fba",
      "fba_libretro",
      "mame",
      "mame-advmame",
      "mame-libretro",
      "mame-mame4all",
      "mess",
    ],
  },
  {
    id: 50,
    type: "Console",
    names: [
      "CoreGrafX",
      "NEC CoreGrafX",
      "PC-Engine DUO",
      "PCE DUO",
      "pcengine",
      "tg16",
    ],
  },
  {
    id: 52,
    type: "Console Portable",
    names: [
      "Electronic Handheld Games",
      "G&W",
      "Game & Watch",
      "Game and Watch",
      "Game'n'Watch",
      "gameandwatch",
      "gw",
      "GW",
      "Nintendo Game & Watch",
      "Nintendo Game and Watch",
      "Nintendo Game'n'Watch",
    ],
  },
  {
    id: 53,
    type: "Arcade",
    names: [
      "arcade",
      "atomiswave",
      "Atomiswave",
      "fba",
      "fba_libretro",
      "mame",
      "mame-advmame",
      "mame-libretro",
      "mame-mame4all",
      "mess",
      "Sammy Atomiswave",
    ],
  },
  {
    id: 54,
    type: "Arcade",
    names: [
      "arcade",
      "fba",
      "fba_libretro",
      "mame",
      "mame-advmame",
      "mame-libretro",
      "mame-mame4all",
      "mess",
      "Model 2",
      "Model II",
      "Sega Model 2",
      "Sega Model II",
    ],
  },
  {
    id: 55,
    type: "Arcade",
    names: [
      "arcade",
      "fba",
      "fba_libretro",
      "mame",
      "mame-advmame",
      "mame-libretro",
      "mame-mame4all",
      "mess",
      "Model 3",
      "Model III",
      "model3",
      "Sega Model 3",
      "Sega Model III",
    ],
  },
  {
    id: 56,
    type: "Arcade",
    names: [
      "arcade",
      "fba",
      "mame",
      "mame-advmame",
      "mame-libretro",
      "mame-mame4all",
      "mess",
      "naomi",
      "Naomi",
      "Sega Naomi",
    ],
  },
  {
    id: 57,
    type: "Console",
    names: [
      "Playstation",
      "PS One",
      "psx",
      "PSX",
      "Sony Playstation",
      "Sony PlayStation",
      "Sony PS One",
      "Sony PSX",
    ],
  },
  {
    id: 58,
    type: "Console",
    names: [
      "Playstation 2",
      "Playstation II",
      "ps2",
      "PS2",
      "Sony Playstation 2",
      "Sony PlayStation 2",
      "Sony Playstation II",
      "Sony PS2",
    ],
  },
  {
    id: 59,
    type: "Console",
    names: [
      "Playstation 3",
      "Playstation III",
      "ps3",
      "PS3",
      "Sony Playstation 3",
      "Sony Playstation III",
      "Sony PS3",
    ],
  },
  {
    id: 60,
    type: "Console",
    names: [
      "Playstation 4",
      "Playstation IV",
      "PS4",
      "Sony Playstation 4",
      "Sony Playstation IV",
      "Sony PS4",
    ],
  },
  {
    id: 61,
    type: "Console Portable",
    names: [
      "Playstation Portable",
      "PS Portable",
      "psp",
      "PSP",
      "Sony Playstation Portable",
      "Sony PS Portable",
      "Sony PSP",
    ],
  },
  {
    id: 62,
    type: "Console Portable",
    names: [
      "Playstation Vita",
      "PS Vita",
      "Sony Playstation Vita",
      "Sony PS Vita",
      "Sony Vita",
      "Vita",
    ],
  },
  {
    id: 63,
    type: "Smartphone",
    names: ["Android"],
  },
  {
    id: 64,
    type: "Ordinateur",
    names: [
      "A1000",
      "A1200",
      "A2000",
      "A3000",
      "A4000",
      "A500",
      "A500+",
      "A600",
      "amiga",
      "Amiga",
      "Amiga 1000",
      "Amiga 1200",
      "Amiga 2000",
      "Amiga 3000",
      "Amiga 4000",
      "Amiga 500",
      "Amiga 500+",
      "Amiga 600",
      "amiga600",
      "Commodore A1000",
      "Commodore A1200",
      "Commodore A2000",
      "Commodore A3000",
      "Commodore A4000",
      "Commodore A500",
      "Commodore A500+",
      "Commodore A600",
      "Commodore Amiga",
      "Commodore Amiga 1000",
      "Commodore Amiga 1200",
      "Commodore Amiga 2000",
      "Commodore Amiga 3000",
      "Commodore Amiga 4000",
      "Commodore Amiga 500",
      "Commodore Amiga 500+",
      "Commodore Amiga 600",
    ],
  },
  {
    id: 65,
    type: "Ordinateur",
    names: [
      "464 Plus",
      "464+",
      "6128 Plus",
      "6128+",
      "Amstrad 464 Plus",
      "Amstrad 464+",
      "Amstrad 6128 Plus",
      "Amstrad 6128+",
      "Amstrad CPC",
      "Amstrad CPC 464",
      "Amstrad CPC 464 Plus",
      "Amstrad CPC 464+",
      "Amstrad CPC 472",
      "Amstrad CPC 6128",
      "Amstrad CPC 6128 Plus",
      "Amstrad CPC 6128+",
      "Amstrad CPC 664",
      "amstradcpc",
      "CPC",
      "CPC 464",
      "CPC 464 Plus",
      "CPC 464+",
      "CPC 472",
      "CPC 6128",
      "CPC 6128 Plus",
      "CPC 6128+",
      "CPC 664",
    ],
  },
  {
    id: 66,
    type: "Ordinateur",
    names: ["c64", "C64", "Commodore 128", "Commodore 64"],
  },
  {
    id: 67,
    type: "Console",
    names: [
      "Epoch Super Cassette Vision",
      "scv",
      "Super Cassette Vision",
      "Yeno Super Cassette Vision",
    ],
  },
  {
    id: 68,
    type: "Arcade",
    names: ["Neo-Geo MVS", "SNK Neo Geo MVS", "SNK Neo-Geo MVS"],
  },
  {
    id: 69,
    type: "Arcade",
    names: [
      "arcade",
      "fba",
      "fba_libretro",
      "mame",
      "mame-advmame",
      "mame-libretro",
      "mame-mame4all",
      "mess",
      "Sega ST-V",
      "ST-V",
    ],
  },
  {
    id: 70,
    type: "Console",
    names: [
      "Neo-geo CD",
      "Neo-Geo CD",
      "Neo-geo CD-Rom",
      "neogeocd",
      "SNK Neo Geo CD",
      "SNK Neo-geo CD",
      "SNK Neo-geo CD-Rom",
    ],
  },
  {
    id: 72,
    type: "Console",
    names: ["NEC PC-FX", "PC-FX", "pcfx"],
  },
  {
    id: 73,
    type: "Ordinateur",
    names: ["c64", "Commodore Vic-20", "Commodore VIC-20", "Vic-20", "vic20"],
  },
  {
    id: 74,
    type: "Console",
    names: ["Casio PV-1000", "PV-1000", "pv1000"],
  },
  {
    id: 75,
    type: "Emulation Arcade",
    names: [
      "AdvanceMAME",
      "AdvMAME",
      "arcade",
      "Arcade",
      "fba",
      "FBA",
      "fba_libretro",
      "FBA-LibRetro",
      "fbneo",
      "Final Burn Alpha",
      "HBMAME",
      "mame",
      "Mame",
      "MAME",
      "mame-advmame",
      "MAME-ADVMAME",
      "mame-libretro",
      "MAME-LibRetro",
      "mame-mame4all",
      "MAME-MAME4ALL",
      "MAME4ALL",
      "mess",
      "MESS",
      "MiSFiT MAME",
    ],
  },
  {
    id: 76,
    type: "Ordinateur",
    names: [
      "Sinclair ZX Spectrum",
      "Sinclair ZX-Spectrum",
      "ZX Spectrum",
      "ZX-Spectrum",
      "zxspectrum",
    ],
  },
  {
    id: 77,
    type: "Ordinateur",
    names: ["Sinclair ZX-81", "Sinclair ZX81", "ZX-81", "zx81", "ZX81"],
  },
  {
    id: 78,
    type: "Console Portable",
    names: ["Adventure Vision", "Entex Adventure Vision"],
  },
  {
    id: 79,
    type: "Ordinateur",
    names: ["Sharp X68000", "Sharp X68k", "x68000", "X68000", "X68k"],
  },
  {
    id: 80,
    type: "Console",
    names: [
      "Channel F",
      "channelf",
      "Fairchild Channel F",
      "Fairchild VES",
      "Fairchild Video Entertainment System",
      "VES",
      "Video Entertainment System",
    ],
  },
  {
    id: 81,
    type: "Console",
    names: ["Action Max", "World of Wonder Action Max", "WoW Action Max"],
  },
  {
    id: 82,
    type: "Console Portable",
    names: [
      "Neo-geo PC",
      "Neo-geo Pocket Color",
      "Neo-Geo Pocket Color",
      "ngpc",
      "NGPC",
      "SNK Neo Geo Pocket Color",
      "SNK Neo-geo PC",
      "SNK Neo-geo Pocket Color",
      "SNK NGPC",
    ],
  },
  {
    id: 83,
    type: "Ordinateur",
    names: ["Aamber Pegasus"],
  },
  {
    id: 84,
    type: "Ordinateur",
    names: ["Acorn Archimedes", "archimedes", "Archimedes"],
  },
  {
    id: 85,
    type: "Ordinateur",
    names: ["Acorn Electron", "Electron"],
  },
  {
    id: 86,
    type: "Ordinateur",
    names: [
      "Apple 1",
      "Apple 2",
      "Apple 2+",
      "Apple 2C",
      "Apple 2C Plus",
      "Apple 2C+",
      "Apple 2E",
      "Apple 2GS",
      "Apple 3",
      "Apple I",
      "Apple II",
      "Apple II+",
      "Apple IIC",
      "Apple IIC Plus",
      "Apple IIC+",
      "Apple IIE",
      "Apple IIGS",
      "Apple III",
      "apple2",
    ],
  },
  {
    id: 87,
    type: "Console",
    names: ["Amstrad GX-4000", "Amstrad GX4000", "GX-4000", "gx4000", "GX4000"],
  },
  {
    id: 88,
    type: "Ordinateur",
    names: [
      "Camputers Lynx",
      "Camputers Lynx 128",
      "Camputers Lynx 48",
      "Camputers Lynx 96",
      "Lynx 128",
      "Lynx 48",
      "Lynx 96",
    ],
  },
  {
    id: 89,
    type: "Ordinateur",
    names: ["Adam", "Coleco Adam", "Coleco ADAM"],
  },
  {
    id: 90,
    type: "Console Portable",
    names: ["Cougar Boy", "Creatronic Mega Duck", "Mega Duck", "megaduck"],
  },
  {
    id: 91,
    type: "Ordinateur",
    names: [
      "dragon",
      "Dragon 32",
      "Dragon 32-64",
      "Dragon 32/64",
      "Dragon 64",
      "Dragon Data Dragon",
      "dragon32",
    ],
  },
  {
    id: 92,
    type: "Ordinateur",
    names: [
      "Colour Genie",
      "EACA Colour Genie",
      "EACA EG-2000",
      "EACA EG-2000 Colour Genie",
      "EACA EG2000 Colour Genie",
      "EG-2000",
      "EG2000 Colour Genie",
    ],
  },
  {
    id: 93,
    type: "Ordinateur",
    names: [
      "bk",
      "BK",
      "BK-0010",
      "BK-0010.01",
      "BK-0010Sh",
      "BK-0011",
      "BK-0011M",
      "Electonika BK",
      "Electonika BK-0010",
      "Electonika BK-0010.01",
      "Electonika BK-0010Sh",
      "Electonika BK-0011",
      "Electonika BK-0011M",
      "Elektronika BK",
    ],
  },
  {
    id: 94,
    type: "Console",
    names: [
      "Advision Home Arcade",
      "Arcadia 2001",
      "Bandai Arcadia",
      "Dynavision",
      "Emerson 2001",
      "Emerson Arcadia 2001",
      "Emerson Radio Arcadia 2001",
      "GrandStand Video Master",
      "Hanimex MPT-03",
      "HMG-2650",
      "Home Arcade Centre",
      "Intelligent Game MPT-03",
      "Intercord XL 2000 System",
      "Intervision 2001",
      "ITMC MPT-03",
      "Leisure-Vision",
      "Leonardo",
      "Ormatu 2001",
      "P.I.C Ekusera",
      "Palladium Video Computer Game",
      "Polybrain Video Computer Game",
      "Poppy MPT-03 Tele Computer Spiel",
      "Prestige Video Computer Game MPT-03",
      "Rowtron 2000",
      "Rowtron Video Computer Game MPT-03",
      "Schmid TVG-2000",
      "Sheen Home Video Centre 2001",
      "Soundic MPT-03",
      "Tele Brain",
      "Tele-computer Cosmos",
      "Tele-Fever",
      "Tempest Video Computer Game",
      "Tobby MPT-03",
      "Trakton Computer Video Game",
      "Tryom Video Game Center",
      "Tunix Home Arcade",
      "UVI Compu-Game",
    ],
  },
  {
    id: 95,
    type: "Console Portable",
    names: ["Epoch Game Pocket Computer", "Game Pocket Computer"],
  },
  {
    id: 96,
    type: "Ordinateur",
    names: ["Exelvision EXL 100", "EXL 100", "exl100"],
  },
  {
    id: 97,
    type: "Ordinateur",
    names: [
      "FM-7",
      "FM-77",
      "FM-77AV",
      "FM-8",
      "FM-NEW 7",
      "fm7",
      "Fujitsu FM-7",
      "Fujitsu Micro 7",
    ],
  },
  {
    id: 98,
    type: "Console",
    names: ["Casio Loopy", "loopy", "Loopy"],
  },
  {
    id: 99,
    type: "Ordinateur",
    names: [
      "Commodore 16",
      "Commodore 16 & Plus4",
      "Commodore Minus/60",
      "Commodore Plus 4",
      "Commodore Plus/4",
      "Minus/60",
      "Plus/4",
    ],
  },
  {
    id: 100,
    type: "Console",
    names: [
      "Funtech Super A'Can",
      "Funtech Super Acan",
      "Super A'can",
      "Super A'Can",
      "superacan",
    ],
  },
  {
    id: 101,
    type: "Console Portable",
    names: ["Game Park 32", "GamePark 32", "gp32", "GP32"],
  },
  {
    id: 102,
    type: "Console",
    names: ["GCE Vectrex", "vectrex", "Vectrex"],
  },
  {
    id: 103,
    type: "Console Portable",
    names: [
      "Game Master",
      "Game Tronic",
      "Hartung Game Master",
      "Super Game",
      "Systema 2000",
    ],
  },
  {
    id: 104,
    type: "Console",
    names: [
      "Brandt Japac JO7400",
      "Brandt Jopac",
      "C7420",
      "Continental Edision Jopac",
      "Continental Edison Jopac JO 1450",
      "G7000",
      "G7200",
      "G7400",
      "G7401",
      "Japac JO 7400",
      "JO 1450",
      "JO 7400",
      "Jopac",
      "Jopac JO 1450",
      "Magnavox Odyssey 2",
      "Magnavox Odyssey2",
      "o2em",
      "odyssey2",
      "Odyssey2",
      "Philips Videopac",
      "Philips Videopac C52",
      "Philips Videopac C7420",
      "Philips Videopac G7000",
      "Philips Videopac G7200",
      "Philips Videopac G7401",
      "Philips Videopac N60",
      "Philips Videopac Plus G7400",
      "Philips Videopac+ G7400",
      "Radiola Videopac",
      "Radiola Videopac Jet 25",
      "Radiola Videopac Jet 27",
      "Radiola Videopac Jet 47",
      "Radiola Videopac Jet 471",
      "Radiola Videopac Jet 74+",
      "Radiola Videopac Jet 741+",
      "Sabe Jopac",
      "Schneider Videopac",
      "Schneider Videopac 7200",
      "Siera Videopac",
      "videopac",
      "Videopac",
      "Videopac 7200",
      "Videopac C52",
      "Videopac C7420",
      "Videopac G7000",
      "Videopac G7200",
      "Videopac G7401",
      "Videopac Jet 25",
      "Videopac Jet 27",
      "Videopac Jet 47",
      "Videopac Jet 471",
      "Videopac Jet 74+",
      "Videopac Jet 741+",
      "Videopac N60",
      "Videopac+ G7400",
    ],
  },
  {
    id: 105,
    type: "Console",
    names: [
      "NEC PC Engine SuperGrafx",
      "NEC SuperGrafx",
      "PC Engine SuperGrafx",
      "supergrafx",
      "SuperGrafx",
    ],
  },
  {
    id: 106,
    type: "Console",
    names: [
      "Famicom Disk System",
      "Famikom Disk System",
      "Family Computer Disk System",
      "Famiri Konpyuta Disuku Shisutemu",
      "FCD",
      "FCDS",
      "fds",
      "FDS",
      "FKDS",
      "Nintendo Famicom Disk System",
      "Nintendo Famikom Disk System",
      "Nintendo Family Computer Disk System",
      "Nintendo Famiri Konpyuta Disuku Shisutemu",
      "Nintendo FCD",
      "Nintendo FCDS",
      "Nintendo FDS",
      "Nintendo FKDS",
    ],
  },
  {
    id: 107,
    type: "Console",
    names: [
      "BS-X",
      "Nintendo BS-X",
      "Nintendo Satellaview",
      "satellaview",
      "Satellaview",
      "snes",
    ],
  },
  {
    id: 108,
    type: "Accessoire",
    names: ["Bandai Sufami Turbo", "snes", "sufami", "Sufami Turbo"],
  },
  {
    id: 109,
    type: "Console",
    names: [
      "Othello Multivisio",
      "SC 3000",
      "Sega Game 1000",
      "Sega SG-1000",
      "sg-1000",
      "SG-1000",
      "SG-1000 2",
      "SG-1000 II",
      "sg1000",
    ],
  },
  {
    id: 110,
    type: "Autres",
    names: ["Nintendo Power"],
  },
  {
    id: 111,
    type: "Ordinateur",
    names: [
      "amiga",
      "Amiga (AGA)",
      "Amiga AGA",
      "amiga1200",
      "Commodore Amiga",
    ],
  },
  {
    id: 112,
    type: "Arcade",
    names: [
      "arcade",
      "fba",
      "fba_libretro",
      "mame",
      "mame-advmame",
      "mame-libretro",
      "mame-mame4all",
      "mess",
      "Taito Type X",
      "Taito Type X+",
      "Taito Type X2 Satellite Terminal",
      "Taito Type X3",
      "Taito Type X7",
      "Taito Type XZero",
      "Taito Type-X2",
      "Type X",
    ],
  },
  {
    id: 113,
    type: "Ordinateur",
    names: ["Microsoft MSX", "Microsoft MSX1", "msx", "MSX", "msx1", "MSX1"],
  },
  {
    id: 114,
    type: "Console",
    names: [
      "NEC PC Engine CD",
      "NEC PC Engine CD-Rom",
      "NEC PC Engine-CD",
      "NEC TurboGrafx-CD",
      "PC Engine CD",
      "PC Engine CD-Rom",
      "pce-cd",
      "pcenginecd",
      "tg-cd",
    ],
  },
  {
    id: 115,
    type: "Console",
    names: [
      "Intelliputer",
      "intellivision",
      "Intellivision",
      "Intellivision 2",
      "Intellivision II",
      "INTV III",
      "INTV Super Pro System",
      "Mattel ECS",
      "Mattel Intelliputer",
      "Mattel Intellivision",
      "Mattel Intellivision 2",
      "Mattel Intellivision II",
      "Super Pro System",
    ],
  },
  {
    id: 116,
    type: "Ordinateur",
    names: ["Microsoft MSX2", "msx", "msx2", "MSX2"],
  },
  {
    id: 117,
    type: "Ordinateur",
    names: [
      "Microsoft MSX2+",
      "Microsoft MSX2Plus",
      "msx",
      "msx2",
      "MSX2+",
      "MSX2Plus",
    ],
  },
  {
    id: 118,
    type: "Ordinateur",
    names: [
      "Microsoft MSX",
      "Microsoft MSX R Turbo",
      "msx",
      "MSX Turbo R",
      "MSX-R Turbo",
      "msxturbor",
    ],
  },
  {
    id: 119,
    type: "Accessoire",
    names: [
      "GameBoy Advance e-Reader",
      "GB Advance e-Reader",
      "GBA e-Reader",
      "Nintendo e-Reader",
      "Nintendo GameBoy Advance e-Reader",
      "Nintendo GB Advance e-Reader",
      "Nintendo GBA e-Reader",
    ],
  },
  {
    id: 120,
    type: "Console",
    names: ["V.Smile", "vsmile", "VTech V.Smile"],
  },
  {
    id: 121,
    type: "Console Portable",
    names: ["Game.com", "Tiger Game.com"],
  },
  {
    id: 122,
    type: "Console",
    names: [
      "64 DD",
      "64dd",
      "n64",
      "N64 DD",
      "Nintendo 64 DD",
      "Nintendo 64DD",
    ],
  },
  {
    id: 123,
    type: "Machine Virtuelle",
    names: ["residualvm", "ResidualVM", "scummvm", "ScummVM"],
  },
  {
    id: 124,
    type: "Ordinateur",
    names: ["Mikrosha", "Mikrosha Computer", "Radio-86RK Mikrosha"],
  },
  {
    id: 125,
    type: "Ordinateur",
    names: ["Pecom 64"],
  },
  {
    id: 126,
    type: "Ordinateur",
    names: [
      "Ace 4000",
      "Ace4000",
      "Jupiter Ace",
      "Jupiter ACE",
      "Jupiter Ace 4000",
    ],
  },
  {
    id: 127,
    type: "Accessoire",
    names: [
      "gb",
      "Nintendo Super Game Boy",
      "Nintendo Super GameBoy",
      "Nintendo Super GG",
      "Super Game Boy",
      "Super GameBoy",
      "Super GB",
    ],
  },
  {
    id: 128,
    type: "Accessoire",
    names: [
      "gb",
      "Nintendo Super Game Boy",
      "Nintendo Super GameBoy 2",
      "Nintendo Super GG 2",
      "Super Game Boy 2",
      "Super GameBoy 2",
      "Super GB 2",
    ],
  },
  {
    id: 129,
    type: "Ordinateur",
    names: [
      "amiga",
      "Amiga CDTV",
      "amigacdtv",
      "Amliga CDTV",
      "CDTV",
      "Commodore Amiga CDTV",
      "Commodore CDTV",
    ],
  },
  {
    id: 130,
    type: "Console",
    names: ["amiga", "Amiga CD32", "amigacd32", "Commodore Amiga CD32"],
  },
  {
    id: 131,
    type: "Ordinateur",
    names: [
      "Eureka Adresstal",
      "Eureka Nova 64",
      "Eureka Oric Adresstal",
      "Eureka Oric Atmos",
      "Eureka Oric Nova 64",
      "Eureka Oric Telestrat",
      "Eureka Telestrat",
      "oric",
      "Oric 1 / Atmos",
      "Oric Atmos",
      "Oric-1",
      "Oric-I",
      "Tangerince Oric Atmos",
      "Tangerine Oric",
      "Tangerine Oric-1",
      "Tangerine Oric-I",
    ],
  },
  {
    id: 133,
    type: "Console",
    names: ["CD-i", "CD-I", "cdi", "Philips CD-i", "Philips CD-I"],
  },
  {
    id: 134,
    type: "Accessoire",
    names: [
      "amiga",
      "Amiga CD",
      "amigacd32",
      "Commodore Amiga CD",
      "Commodore Amiga CD32",
    ],
  },
  {
    id: 135,
    type: "Ordinateur",
    names: [
      "DOS",
      "DosBox",
      "eXoDos",
      "Microsoft DOS",
      "Microsoft MS-DOS",
      "MS-Dos",
      "MS-DOS",
      "pc",
      "PC",
      "PC Dos",
      "PC-DOS",
      "PrBoom",
      "Total DOS",
      "Total DOS Collection",
    ],
  },
  {
    id: 136,
    type: "Ordinateur",
    names: [
      "Microsoft Windows 3.0",
      "Microsoft Windows 3.1",
      "Microsoft Windows 3.x",
      "PC Win3.xx",
      "W3.0",
      "W3.1",
      "Win 3.0",
      "Win 3.1",
      "Windows 3.0",
      "Windows 3.1",
      "Windows 3.X",
    ],
  },
  {
    id: 137,
    type: "Ordinateur",
    names: [
      "Microsoft Windows 95",
      "Microsoft Windows 98",
      "Microsoft Windows 98SE",
      "Microsoft Windows 98SE2",
      "Microsoft Windows Millenium",
      "PC Win9X",
      "W95",
      "W98",
      "W98SE",
      "W98SE2",
      "Win 95",
      "Win 98",
      "Win 98SE",
      "Win 98SE2",
      "Win Millenium",
      "Windows 95",
      "Windows 98",
      "Windows 98SE",
      "Windows 98SE2",
      "Windows Millenium",
    ],
  },
  {
    id: 138,
    type: "Ordinateur",
    names: [
      "Microsoft Windows",
      "Microsoft Windows 10",
      "Microsoft Windows 2000",
      "Microsoft Windows 7",
      "Microsoft Windows 8",
      "Microsoft Windows 8.1",
      "Microsoft Windows Vista",
      "Microsoft Windows XP",
      "PC Windows",
      "W10",
      "W2000",
      "W7",
      "W8",
      "W8.1",
      "Win 10",
      "Win 2000",
      "Win 7",
      "Win 8",
      "Win 8.1",
      "Win Vista",
      "Win XP",
      "Windows",
      "Windows 10",
      "Windows 2000",
      "Windows 7",
      "Windows 8",
      "Windows 8.1",
      "Windows Vista",
      "Windows XP",
      "WXP",
    ],
  },
  {
    id: 139,
    type: "Console",
    names: ["amiga", "Amiga CD32 (hack)", "amigacd32", "Commodore Amiga CD32"],
  },
  {
    id: 141,
    type: "Ordinateur",
    names: [
      "MO5",
      "MO5E",
      "MO5NR",
      "MO6",
      "Olivetti Prodest PC128",
      "Thomson MO",
      "Thomson MO/TO",
      "Thomson MO5",
      "Thomson MO5E",
      "Thomson MO5NR",
      "Thomson MO6",
      "Thomson TO",
      "Thomson TO7",
      "Thomson TO7-70",
      "Thomson TO8",
      "Thomson TO8D",
      "Thomson TO9",
      "Thomson TO9 Plus",
      "Thomson TO9+",
      "TO7",
      "TO7-70",
      "to8",
      "TO8",
      "TO8D",
      "TO9",
      "TO9 Plus",
      "TO9+",
    ],
  },
  {
    id: 142,
    type: "Console & Arcade",
    names: [
      "Neo-Geo",
      "Neo-Geo AES",
      "Neo-Geo MVS",
      "neogeo",
      "SNK Neo Geo",
      "SNK Neo-Geo",
      "SNK Neo-Geo AES",
      "SNK Neo-Geo MVS",
    ],
  },
  {
    id: 143,
    type: "Flipper",
    names: ["Pinball FX2"],
  },
  {
    id: 144,
    type: "Ordinateur",
    names: [
      "coco",
      "CoCo",
      "Tandy TRS-80",
      "Tandy TRS-80 CoCo",
      "Tandy TRS-80 Color Computer",
      "TRS-80 CoCo",
      "TRS-80 Color Computer",
      "trs80coco",
    ],
  },
  {
    id: 145,
    type: "Ordinateur",
    names: ["Linux"],
  },
  {
    id: 146,
    type: "Ordinateur",
    names: [
      "Apple Mac OS",
      "Apple Mac-OS",
      "Apple Mac-OSX",
      "Apple OS",
      "Apple OSX",
      "Mac OS",
      "Mac-OS",
      "Mac-OSX",
      "macintosh",
      "OSX",
    ],
  },
  {
    id: 147,
    type: "Arcade",
    names: [
      "arcade",
      "fba",
      "fba_libretro",
      "mame",
      "mame-advmame",
      "mame-libretro",
      "mame-mame4all",
      "mess",
      "Sega Classics",
    ],
  },
  {
    id: 148,
    type: "Arcade",
    names: [
      "arcade",
      "fba",
      "fba_libretro",
      "Irem Classics",
      "mame",
      "mame-advmame",
      "mame-libretro",
      "mame-mame4all",
      "mess",
    ],
  },
  {
    id: 149,
    type: "Arcade",
    names: [
      "arcade",
      "fba",
      "fba_libretro",
      "mame",
      "mame-advmame",
      "mame-libretro",
      "mame-mame4all",
      "mess",
      "Seta",
      "SETA",
    ],
  },
  {
    id: 150,
    type: "Arcade",
    names: [
      "arcade",
      "fba",
      "fba_libretro",
      "mame",
      "mame-advmame",
      "mame-libretro",
      "mame-mame4all",
      "mess",
      "Midway Classics",
      "Williams Classics",
    ],
  },
  {
    id: 151,
    type: "Arcade",
    names: [
      "arcade",
      "Capcom Classics",
      "fba",
      "fba_libretro",
      "mame",
      "mame-advmame",
      "mame-libretro",
      "mame-mame4all",
      "mess",
    ],
  },
  {
    id: 152,
    type: "Arcade",
    names: [
      "8ing/Raizing",
      "arcade",
      "Eighting / Raizing",
      "Eighting/Raizing",
      "fba",
      "fba_libretro",
      "mame",
      "mame-advmame",
      "mame-libretro",
      "mame-mame4all",
      "mess",
      "R8zing",
      "Raizing",
      "Raizing/8ing",
      "Raizing/Eighting",
    ],
  },
  {
    id: 153,
    type: "Arcade",
    names: [
      "arcade",
      "fba",
      "fba_libretro",
      "mame",
      "mame-advmame",
      "mame-libretro",
      "mame-mame4all",
      "mess",
      "Tecmo",
      "TECMO",
    ],
  },
  {
    id: 154,
    type: "Arcade",
    names: [
      "arcade",
      "fba",
      "fba_libretro",
      "mame",
      "mame-advmame",
      "mame-libretro",
      "mame-mame4all",
      "mess",
      "SNK Classics",
    ],
  },
  {
    id: 155,
    type: "Arcade",
    names: [
      "arcade",
      "fba",
      "fba_libretro",
      "mame",
      "mame-advmame",
      "mame-libretro",
      "mame-mame4all",
      "mess",
      "Namco Classics",
    ],
  },
  {
    id: 156,
    type: "Arcade",
    names: [
      "arcade",
      "fba",
      "fba_libretro",
      "mame",
      "mame-advmame",
      "mame-libretro",
      "mame-mame4all",
      "mess",
      "Namco System 22",
      "System 22",
    ],
  },
  {
    id: 157,
    type: "Arcade",
    names: [
      "arcade",
      "fba",
      "fba_libretro",
      "mame",
      "mame-advmame",
      "mame-libretro",
      "mame-mame4all",
      "mess",
      "Taito Classics",
    ],
  },
  {
    id: 158,
    type: "Arcade",
    names: [
      "arcade",
      "fba",
      "fba_libretro",
      "Konami Classics",
      "Konami e-AMUSEMENT",
      "mame",
      "mame-advmame",
      "mame-libretro",
      "mame-mame4all",
      "mess",
    ],
  },
  {
    id: 159,
    type: "Arcade",
    names: [
      "arcade",
      "fba",
      "fba_libretro",
      "Jaleco",
      "mame",
      "mame-advmame",
      "mame-libretro",
      "mame-mame4all",
      "mess",
    ],
  },
  {
    id: 160,
    type: "Arcade",
    names: [
      "arcade",
      "Atari Classics",
      "fba",
      "fba_libretro",
      "mame",
      "mame-advmame",
      "mame-libretro",
      "mame-mame4all",
      "mess",
    ],
  },
  {
    id: 161,
    type: "Arcade",
    names: [
      "arcade",
      "fba",
      "fba_libretro",
      "mame",
      "mame-advmame",
      "mame-libretro",
      "mame-mame4all",
      "mess",
      "Nintendo Classics",
    ],
  },
  {
    id: 162,
    type: "Arcade",
    names: [
      "arcade",
      "Data East Classics",
      "fba",
      "fba_libretro",
      "mame",
      "mame-advmame",
      "mame-libretro",
      "mame-mame4all",
      "mess",
    ],
  },
  {
    id: 163,
    type: "Arcade",
    names: [
      "arcade",
      "fba",
      "fba_libretro",
      "mame",
      "mame-advmame",
      "mame-libretro",
      "mame-mame4all",
      "mess",
      "NMK",
    ],
  },
  {
    id: 164,
    type: "Arcade",
    names: [
      "arcade",
      "fba",
      "fba_libretro",
      "mame",
      "mame-advmame",
      "mame-libretro",
      "mame-mame4all",
      "mess",
      "Sammy Classics",
    ],
  },
  {
    id: 165,
    type: "Arcade",
    names: [
      "arcade",
      "Exidy",
      "Exidy Sorcerer",
      "fba",
      "fba_libretro",
      "mame",
      "mame-advmame",
      "mame-libretro",
      "mame-mame4all",
      "mess",
    ],
  },
  {
    id: 166,
    type: "Arcade",
    names: [
      "Acclaim",
      "arcade",
      "fba",
      "fba_libretro",
      "mame",
      "mame-advmame",
      "mame-libretro",
      "mame-mame4all",
      "mess",
    ],
  },
  {
    id: 167,
    type: "Arcade",
    names: [
      "arcade",
      "fba",
      "fba_libretro",
      "mame",
      "mame-advmame",
      "mame-libretro",
      "mame-mame4all",
      "mess",
      "Psikyo",
    ],
  },
  {
    id: 168,
    type: "Arcade",
    names: [
      "arcade",
      "fba",
      "fba_libretro",
      "mame",
      "mame-advmame",
      "mame-libretro",
      "mame-mame4all",
      "mess",
      "non Jeu",
    ],
  },
  {
    id: 169,
    type: "Arcade",
    names: [
      "arcade",
      "fba",
      "fba_libretro",
      "mame",
      "mame-advmame",
      "mame-libretro",
      "mame-mame4all",
      "mess",
      "Technos",
    ],
  },
  {
    id: 170,
    type: "Arcade",
    names: [
      "American Laser Games",
      "arcade",
      "fba",
      "fba_libretro",
      "mame",
      "mame-advmame",
      "mame-libretro",
      "mame-mame4all",
      "mess",
    ],
  },
  {
    id: 171,
    type: "Console",
    names: [
      "Atari Jaguar CD",
      "Atari Jaguar CD-Rom",
      "Jaguar CD",
      "Jaguar CD-Rom",
    ],
  },
  {
    id: 172,
    type: "Console Portable",
    names: [
      "Playstation minis",
      "Playstation Minis",
      "PS Minis",
      "psp",
      "Sony Playstation Minis",
      "Sony PS Minis",
      "Sony PSP Minis",
    ],
  },
  {
    id: 173,
    type: "Arcade",
    names: [
      "arcade",
      "Dynax",
      "fba",
      "fba_libretro",
      "mame",
      "mame-advmame",
      "mame-libretro",
      "mame-mame4all",
      "mess",
    ],
  },
  {
    id: 174,
    type: "Arcade",
    names: [
      "arcade",
      "fba",
      "fba_libretro",
      "Kaneko",
      "mame",
      "mame-advmame",
      "mame-libretro",
      "mame-mame4all",
      "mess",
    ],
  },
  {
    id: 175,
    type: "Arcade",
    names: [
      "arcade",
      "fba",
      "fba_libretro",
      "mame",
      "mame-advmame",
      "mame-libretro",
      "mame-mame4all",
      "mess",
      "Video System Co.",
    ],
  },
  {
    id: 176,
    type: "Arcade",
    names: [
      "arcade",
      "fba",
      "fba_libretro",
      "IGS",
      "mame",
      "mame-advmame",
      "mame-libretro",
      "mame-mame4all",
      "mess",
    ],
  },
  {
    id: 177,
    type: "Arcade",
    names: [
      "arcade",
      "Comad",
      "fba",
      "fba_libretro",
      "mame",
      "mame-advmame",
      "mame-libretro",
      "mame-mame4all",
      "mess",
    ],
  },
  {
    id: 178,
    type: "Arcade",
    names: [
      "Amcoe",
      "arcade",
      "fba",
      "fba_libretro",
      "mame",
      "mame-advmame",
      "mame-libretro",
      "mame-mame4all",
      "mess",
    ],
  },
  {
    id: 179,
    type: "Arcade",
    names: [
      "arcade",
      "Century Electronics",
      "fba",
      "fba_libretro",
      "mame",
      "mame-advmame",
      "mame-libretro",
      "mame-mame4all",
      "mess",
    ],
  },
  {
    id: 180,
    type: "Arcade",
    names: [
      "arcade",
      "fba",
      "fba_libretro",
      "mame",
      "mame-advmame",
      "mame-libretro",
      "mame-mame4all",
      "mess",
      "Nichibutsu",
    ],
  },
  {
    id: 181,
    type: "Arcade",
    names: [
      "arcade",
      "fba",
      "fba_libretro",
      "mame",
      "mame-advmame",
      "mame-libretro",
      "mame-mame4all",
      "mess",
      "Visco",
    ],
  },
  {
    id: 182,
    type: "Arcade",
    names: [
      "Alpha Denshi Co.",
      "arcade",
      "fba",
      "fba_libretro",
      "mame",
      "mame-advmame",
      "mame-libretro",
      "mame-mame4all",
      "mess",
    ],
  },
  {
    id: 183,
    type: "Arcade",
    names: [
      "arcade",
      "Coleco",
      "fba",
      "fba_libretro",
      "mame",
      "mame-advmame",
      "mame-libretro",
      "mame-mame4all",
      "mess",
    ],
  },
  {
    id: 184,
    type: "Arcade",
    names: [
      "arcade",
      "fba",
      "fba_libretro",
      "mame",
      "mame-advmame",
      "mame-libretro",
      "mame-mame4all",
      "mess",
      "Playchoice",
      "PlayChoice",
    ],
  },
  {
    id: 185,
    type: "Arcade",
    names: [
      "Altus",
      "arcade",
      "Atlus",
      "fba",
      "fba_libretro",
      "mame",
      "mame-advmame",
      "mame-libretro",
      "mame-mame4all",
      "mess",
    ],
  },
  {
    id: 186,
    type: "Arcade",
    names: [
      "arcade",
      "Banpresto",
      "fba",
      "fba_libretro",
      "mame",
      "mame-advmame",
      "mame-libretro",
      "mame-mame4all",
      "mess",
    ],
  },
  {
    id: 187,
    type: "Arcade",
    names: [
      "arcade",
      "fba",
      "fba_libretro",
      "mame",
      "mame-advmame",
      "mame-libretro",
      "mame-mame4all",
      "mess",
      "SemiCom",
    ],
  },
  {
    id: 188,
    type: "Arcade",
    names: [
      "arcade",
      "fba",
      "fba_libretro",
      "mame",
      "mame-advmame",
      "mame-libretro",
      "mame-mame4all",
      "mess",
      "Universal",
    ],
  },
  {
    id: 189,
    type: "Arcade",
    names: [
      "arcade",
      "fba",
      "fba_libretro",
      "mame",
      "mame-advmame",
      "mame-libretro",
      "mame-mame4all",
      "mess",
      "Mitchell",
    ],
  },
  {
    id: 190,
    type: "Arcade",
    names: [
      "arcade",
      "fba",
      "fba_libretro",
      "mame",
      "mame-advmame",
      "mame-libretro",
      "mame-mame4all",
      "mess",
      "Seibu Kaihatsu",
    ],
  },
  {
    id: 191,
    type: "Arcade",
    names: [
      "arcade",
      "fba",
      "fba_libretro",
      "mame",
      "mame-advmame",
      "mame-libretro",
      "mame-mame4all",
      "mess",
      "Toaplan",
    ],
  },
  {
    id: 192,
    type: "Arcade",
    names: [
      "arcade",
      "Cinematronics",
      "fba",
      "fba_libretro",
      "mame",
      "mame-advmame",
      "mame-libretro",
      "mame-mame4all",
      "mess",
    ],
  },
  {
    id: 193,
    type: "Arcade",
    names: [
      "arcade",
      "fba",
      "fba_libretro",
      "Incredible Technologies",
      "mame",
      "mame-advmame",
      "mame-libretro",
      "mame-mame4all",
      "mess",
    ],
  },
  {
    id: 194,
    type: "Arcade",
    names: [
      "arcade",
      "fba",
      "fba_libretro",
      "Gaelco",
      "mame",
      "mame-advmame",
      "mame-libretro",
      "mame-mame4all",
      "mess",
    ],
  },
  {
    id: 195,
    type: "Arcade",
    names: [
      "arcade",
      "fba",
      "fba_libretro",
      "mame",
      "mame-advmame",
      "mame-libretro",
      "mame-mame4all",
      "Mega-Tech",
      "mess",
    ],
  },
  {
    id: 196,
    type: "Arcade",
    names: [
      "arcade",
      "fba",
      "fba_libretro",
      "mame",
      "mame-advmame",
      "mame-libretro",
      "mame-mame4all",
      "Mega-Play",
      "mess",
    ],
  },
  {
    id: 197,
    type: "Flipper",
    names: ["Flipper", "Pinball"],
  },
  {
    id: 198,
    type: "Flipper",
    names: ["Visual Pinball"],
  },
  {
    id: 199,
    type: "Flipper",
    names: ["Future Pinball"],
  },
  {
    id: 200,
    type: "Flipper",
    names: ["the Pinball Arcade"],
  },
  {
    id: 201,
    type: "Flipper",
    names: ["Pinball FX3"],
  },
  {
    id: 202,
    type: "Console",
    names: [
      "Nintendo Super Famicom",
      "snes",
      "Snes - Super Mario World Hacks",
      "Super Nintendo Entertainment System",
      "Super Nintendo Entertainment System - Mario Hacks",
      "Super Nintendo Entertainment System - Super Mario Mario Hacks",
    ],
  },
  {
    id: 203,
    type: "Console",
    names: [
      "genesis",
      "Genesis - Sonic The Hedgehog 2 Hacks",
      "megadrive",
      "Megadrive - Sonic The Hedgehog 2 Hacks",
      "Sega Genesis",
    ],
  },
  {
    id: 205,
    type: "Ordinateur",
    names: [
      "Texas Instruments TI 99/4A",
      "TI-99",
      "TI-99/4A",
      "ti99",
      "ti994a",
    ],
  },
  {
    id: 206,
    type: "Machine Virtuelle",
    names: ["lutro", "Lutro"],
  },
  {
    id: 207,
    type: "Console Portable",
    names: ["supervision", "Watara Supervision"],
  },
  {
    id: 208,
    type: "Ordinateur",
    names: ["NEC PC-9801", "pc98", "Pc98", "PC98", "PC9801"],
  },
  {
    id: 209,
    type: "Arcade",
    names: [
      "arcade",
      "fba",
      "fba_libretro",
      "Gottlieb",
      "mame",
      "mame-advmame",
      "mame-libretro",
      "mame-mame4all",
      "mess",
    ],
  },
  {
    id: 210,
    type: "Console",
    names: ["MSU-1", "SNES MSU-1", "Super Nintendo MSU-1"],
  },
  {
    id: 211,
    type: "Console Portable",
    names: ["pokemini", "PokeMini", "Pokemon mini", "Pokemon Mini"],
  },
  {
    id: 213,
    type: "Ordinateur",
    names: ["MGT SAM Coupe", "SAM Coupe", "samcoupe"],
  },
  {
    id: 214,
    type: "Machine Virtuelle",
    names: ["openbor", "OpenBOR"],
  },
  {
    id: 215,
    type: "Machine Virtuelle",
    names: ["Z-Machine", "zmachine"],
  },
  {
    id: 216,
    type: "Console",
    names: ["uzebox", "Uzebox"],
  },
  {
    id: 217,
    type: "Ordinateur",
    names: ["Apple IIGS", "apple2gs", "appleIIgs"],
  },
  {
    id: 218,
    type: "Ordinateur",
    names: ["spectravideo", "Spectravideo"],
  },
  {
    id: 219,
    type: "Ordinateur",
    names: ["palm", "Palm OS", "palmos"],
  },
  {
    id: 220,
    type: "Ordinateur",
    names: ["Sharp X1", "x1", "X1"],
  },
  {
    id: 221,
    type: "Ordinateur",
    names: ["NEC PC-8801", "pc88"],
  },
  {
    id: 222,
    type: "Machine Virtuelle",
    names: ["TIC-80", "tic80"],
  },
  {
    id: 223,
    type: "Machine Virtuelle",
    names: ["solarus", "Solarus"],
  },
  {
    id: 225,
    type: "Console",
    names: ["Nintendo Switch", "Switch"],
  },
  {
    id: 227,
    type: "Arcade",
    names: [
      "arcade",
      "fba",
      "mame",
      "mame-advmame",
      "mame-libretro",
      "mame-mame4all",
      "mess",
      "Naomi GD",
      "Naomi GD-ROM",
      "naomigd",
      "Sega Naomi-GD",
    ],
  },
  {
    id: 230,
    type: "Arcade",
    names: [
      "arcade",
      "fba",
      "mame",
      "mame-advmame",
      "mame-libretro",
      "mame-mame4all",
      "mess",
      "Naomi 2",
      "naomi2",
      "Sega Naomi 2",
    ],
  },
  {
    id: 231,
    type: "Machine Virtuelle",
    names: ["easyrpg", "EasyRPG"],
  },
  {
    id: 234,
    type: "Machine Virtuelle",
    names: ["Pico-8", "pico8"],
  },
  {
    id: 237,
    type: "Console Portable",
    names: ["pcv2", "Pocket Challenge V2"],
  },
  {
    id: 240,
    type: "Ordinateur",
    names: ["PET"],
  },
  {
    id: 241,
    type: "Console",
    names: ["creativision", "CreatiVision", "crvision"],
  },
  {
    id: 244,
    type: "Machine Virtuelle",
    names: ["LowRes NX", "lowresnx"],
  },
  {
    id: 250,
    type: "Console",
    names: ["pico", "Sega Pico"],
  },
  {
    id: 253,
    type: "Ordinateur",
    names: ["FM Towns", "fmtmarty"],
  },
  {
    id: 258,
    type: "Arcade",
    names: ["Hikaru"],
  },
  {
    id: 261,
    type: "Ordinateur",
    names: ["Philips VG 5000", "vg5000"],
  },
  {
    id: 262,
    type: "Machine Virtuelle",
    names: ["wasm", "WASM-4", "wasm4"],
  },
  {
    id: 263,
    type: "Console Portable",
    names: ["arduboy", "Arduboy"],
  },
  {
    id: 266,
    type: "Console Portable",
    names: ["Gamate"],
  },
  {
    id: 269,
    type: "Emulation Arcade",
    names: ["Tekno Parrot", "TeknoParrot"],
  },
  {
    id: 272,
    type: "Machine Virtuelle",
    names: ["vircon32", "Vircon32"],
  },
  {
    id: 275,
    type: "Machine Virtuelle",
    names: ["voxatron", "Voxatron"],
  },
  {
    id: 278,
    type: "Console",
    names: [
      "nes",
      "Nes - Super Mario Bros. Hacks",
      "Nintendo Entertainment System",
      "Nintendo Entertainment System - Mario Hacks",
      "Nintendo Entertainment System - Super Mario Mario Hacks",
      "Nintendo Famicom",
    ],
  },
  {
    id: 281,
    type: "Console",
    names: ["VC 4000", "Video Computer 4000"],
  },
  {
    id: 284,
    type: "Console",
    names: [
      "Playstation 5",
      "Playstation V",
      "PS5",
      "Sony Playstation 5",
      "Sony Playstation V",
      "Sony PS5",
    ],
  },
  {
    id: 287,
    type: "Ordinateur",
    names: ["p2000t", "P2000T"],
  },
  {
    id: 290,
    type: "Machine Virtuelle",
    names: ["Port", "PrBoom"],
  },
  {
    id: 293,
    type: "Machine Virtuelle",
    names: ["b", "Tamagotchi"],
  },
  {
    id: 296,
    type: "Console",
    names: ["Switch 2"],
  },
  {
    id: 299,
    type: "Arcade",
    names: [
      "arcade",
      "fba",
      "fba_libretro",
      "mame",
      "mame-advmame",
      "mame-libretro",
      "mame-mame4all",
      "mess",
      "Taito G-Net",
    ],
  },
  {
    id: 300,
    type: "Console",
    names: [
      "Cassette Vision",
      "cassettevision",
      "Epoch Cassette Vision",
      "Yeno Cassette Vision",
    ],
  },
  {
    id: 301,
    type: "Console",
    names: ["MSU-MD"],
  },
  {
    id: 302,
    type: "Smartphone",
    names: ["j2me", "J2ME", "Java 2 MicroEdition"],
  },
  {
    id: 305,
    type: "Console",
    names: ["My Vision", "myvision"],
  },
  {
    id: 308,
    type: "Console",
    names: ["V.Smile Pro"],
  },
  {
    id: 311,
    type: "Ordinateur",
    names: ["alice", "Alice"],
  },
  {
    id: 314,
    type: "Ordinateur",
    names: ["Sharp MZ", "sharpmz"],
  },
  {
    id: 317,
    type: "Ordinateur",
    names: [
      "Grandstand Tutor",
      "pyuta",
      "Tomy Pyuta",
      "Tomy Pyuuta",
      "Tomy Tutor",
      "Tutor",
    ],
  },
  {
    id: 320,
    type: "Ordinateur",
    names: ["VZ200 / Laser310"],
  },
] as const satisfies readonly ScreenScraperPlatformReference[];

export const LAUNCHBOX_PLATFORM_REFERENCES = [
  {
    id: 1,
    name: "3DO Interactive Multiplayer",
  },
  {
    id: 2,
    name: "Commodore Amiga",
  },
  {
    id: 3,
    name: "Amstrad CPC",
  },
  {
    id: 4,
    name: "Android",
  },
  {
    id: 5,
    name: "Arcade",
  },
  {
    id: 6,
    name: "Atari 2600",
  },
  {
    id: 7,
    name: "Atari 5200",
  },
  {
    id: 8,
    name: "Atari 7800",
  },
  {
    id: 9,
    name: "Atari Jaguar",
  },
  {
    id: 10,
    name: "Atari Jaguar CD",
  },
  {
    id: 11,
    name: "Atari Lynx",
  },
  {
    id: 12,
    name: "Atari XEGS",
  },
  {
    id: 13,
    name: "ColecoVision",
  },
  {
    id: 14,
    name: "Commodore 64",
  },
  {
    id: 15,
    name: "Mattel Intellivision",
  },
  {
    id: 16,
    name: "Apple iOS",
  },
  {
    id: 17,
    name: "Apple Mac OS",
  },
  {
    id: 18,
    name: "Microsoft Xbox",
  },
  {
    id: 19,
    name: "Microsoft Xbox 360",
  },
  {
    id: 20,
    name: "Microsoft Xbox One",
  },
  {
    id: 21,
    name: "SNK Neo Geo Pocket",
  },
  {
    id: 22,
    name: "SNK Neo Geo Pocket Color",
  },
  {
    id: 23,
    name: "SNK Neo Geo AES",
  },
  {
    id: 24,
    name: "Nintendo 3DS",
  },
  {
    id: 25,
    name: "Nintendo 64",
  },
  {
    id: 26,
    name: "Nintendo DS",
  },
  {
    id: 27,
    name: "Nintendo Entertainment System",
  },
  {
    id: 28,
    name: "Nintendo Game Boy",
  },
  {
    id: 29,
    name: "Nintendo Game Boy Advance",
  },
  {
    id: 30,
    name: "Nintendo Game Boy Color",
  },
  {
    id: 31,
    name: "Nintendo GameCube",
  },
  {
    id: 32,
    name: "Nintendo Virtual Boy",
  },
  {
    id: 33,
    name: "Nintendo Wii",
  },
  {
    id: 34,
    name: "Nintendo Wii U",
  },
  {
    id: 35,
    name: "Ouya",
  },
  {
    id: 37,
    name: "Philips CD-i",
  },
  {
    id: 38,
    name: "Sega 32X",
  },
  {
    id: 39,
    name: "Sega CD",
  },
  {
    id: 40,
    name: "Sega Dreamcast",
  },
  {
    id: 41,
    name: "Sega Game Gear",
  },
  {
    id: 42,
    name: "Sega Genesis",
  },
  {
    id: 43,
    name: "Sega Master System",
  },
  {
    id: 45,
    name: "Sega Saturn",
  },
  {
    id: 46,
    name: "Sinclair ZX Spectrum",
  },
  {
    id: 47,
    name: "Sony Playstation",
  },
  {
    id: 48,
    name: "Sony Playstation 2",
  },
  {
    id: 49,
    name: "Sony Playstation 3",
  },
  {
    id: 50,
    name: "Sony Playstation 4",
  },
  {
    id: 51,
    name: "Sony Playstation Vita",
  },
  {
    id: 52,
    name: "Sony PSP",
  },
  {
    id: 53,
    name: "Super Nintendo Entertainment System",
  },
  {
    id: 54,
    name: "NEC TurboGrafx-16",
  },
  {
    id: 55,
    name: "WonderSwan",
  },
  {
    id: 56,
    name: "WonderSwan Color",
  },
  {
    id: 57,
    name: "Magnavox Odyssey 2",
  },
  {
    id: 58,
    name: "Fairchild Channel F",
  },
  {
    id: 59,
    name: "BBC Microcomputer System",
  },
  {
    id: 60,
    name: "Memotech MTX512",
  },
  {
    id: 61,
    name: "Camputers Lynx",
  },
  {
    id: 63,
    name: "Tiger Game.com",
  },
  {
    id: 64,
    name: "Oric Atmos",
  },
  {
    id: 65,
    name: "Acorn Electron",
  },
  {
    id: 66,
    name: "Dragon 32/64",
  },
  {
    id: 67,
    name: "Entex Adventure Vision",
  },
  {
    id: 68,
    name: "APF Imagination Machine",
  },
  {
    id: 69,
    name: "Mattel Aquarius",
  },
  {
    id: 70,
    name: "Jupiter Ace",
  },
  {
    id: 71,
    name: "SAM Coup&#xE9;",
  },
  {
    id: 72,
    name: "Enterprise",
  },
  {
    id: 73,
    name: "EACA EG2000 Colour Genie",
  },
  {
    id: 74,
    name: "Acorn Archimedes",
  },
  {
    id: 75,
    name: "Tapwave Zodiac",
  },
  {
    id: 76,
    name: "Atari ST",
  },
  {
    id: 77,
    name: "Bally Astrocade",
  },
  {
    id: 78,
    name: "Magnavox Odyssey",
  },
  {
    id: 79,
    name: "Emerson Arcadia 2001",
  },
  {
    id: 80,
    name: "Sega SG-1000",
  },
  {
    id: 81,
    name: "Epoch Super Cassette Vision",
  },
  {
    id: 82,
    name: "Microsoft MSX",
  },
  {
    id: 83,
    name: "MS-DOS",
  },
  {
    id: 84,
    name: "Windows",
  },
  {
    id: 85,
    name: "Web Browser",
  },
  {
    id: 88,
    name: "Sega Model 2",
  },
  {
    id: 93,
    name: "Namco System 22",
  },
  {
    id: 94,
    name: "Sega Model 3",
  },
  {
    id: 96,
    name: "Sega System 32",
  },
  {
    id: 97,
    name: "Sega System 16",
  },
  {
    id: 98,
    name: "Sammy Atomiswave",
  },
  {
    id: 99,
    name: "Sega Naomi",
  },
  {
    id: 100,
    name: "Sega Naomi 2",
  },
  {
    id: 102,
    name: "Atari 800",
  },
  {
    id: 104,
    name: "Sega Model 1",
  },
  {
    id: 105,
    name: "Sega Pico",
  },
  {
    id: 107,
    name: "Acorn Atom",
  },
  {
    id: 109,
    name: "Amstrad GX4000",
  },
  {
    id: 111,
    name: "Apple II",
  },
  {
    id: 112,
    name: "Apple IIGS",
  },
  {
    id: 114,
    name: "Casio Loopy",
  },
  {
    id: 115,
    name: "Casio PV-1000",
  },
  {
    id: 117,
    name: "Coleco ADAM",
  },
  {
    id: 118,
    name: "Commodore 128",
  },
  {
    id: 119,
    name: "Commodore Amiga CD32",
  },
  {
    id: 120,
    name: "Commodore CDTV",
  },
  {
    id: 121,
    name: "Commodore Plus 4",
  },
  {
    id: 122,
    name: "Commodore VIC-20",
  },
  {
    id: 124,
    name: "Fujitsu FM Towns Marty",
  },
  {
    id: 125,
    name: "GCE Vectrex",
  },
  {
    id: 126,
    name: "Nuon",
  },
  {
    id: 127,
    name: "Mega Duck",
  },
  {
    id: 128,
    name: "Sharp X68000",
  },
  {
    id: 129,
    name: "Tandy TRS-80",
  },
  {
    id: 131,
    name: "Elektronika BK",
  },
  {
    id: 132,
    name: "Epoch Game Pocket Computer",
  },
  {
    id: 133,
    name: "Funtech Super Acan",
  },
  {
    id: 135,
    name: "GamePark GP32",
  },
  {
    id: 136,
    name: "Hartung Game Master",
  },
  {
    id: 137,
    name: "Interton VC 4000",
  },
  {
    id: 138,
    name: "MUGEN",
  },
  {
    id: 139,
    name: "OpenBOR",
  },
  {
    id: 140,
    name: "Philips VG 5000",
  },
  {
    id: 141,
    name: "Philips Videopac&#x2B;",
  },
  {
    id: 142,
    name: "RCA Studio II",
  },
  {
    id: 143,
    name: "ScummVM",
  },
  {
    id: 144,
    name: "Sega Dreamcast VMU",
  },
  {
    id: 145,
    name: "Sega SC-3000",
  },
  {
    id: 146,
    name: "Sega ST-V",
  },
  {
    id: 147,
    name: "Sinclair ZX-81",
  },
  {
    id: 148,
    name: "Sord M5",
  },
  {
    id: 149,
    name: "Texas Instruments TI 99/4A",
  },
  {
    id: 151,
    name: "Pinball",
  },
  {
    id: 152,
    name: "VTech CreatiVision",
  },
  {
    id: 153,
    name: "Watara Supervision",
  },
  {
    id: 154,
    name: "WoW Action Max",
  },
  {
    id: 155,
    name: "ZiNc",
  },
  {
    id: 157,
    name: "Nintendo Famicom Disk System",
  },
  {
    id: 161,
    name: "NEC PC-FX",
  },
  {
    id: 162,
    name: "PC Engine SuperGrafx",
  },
  {
    id: 163,
    name: "NEC TurboGrafx-CD",
  },
  {
    id: 164,
    name: "TRS-80 Color Computer",
  },
  {
    id: 166,
    name: "Nintendo Game &amp; Watch",
  },
  {
    id: 167,
    name: "SNK Neo Geo CD",
  },
  {
    id: 168,
    name: "Nintendo Satellaview",
  },
  {
    id: 169,
    name: "Taito Type X",
  },
  {
    id: 170,
    name: "XaviXPORT",
  },
  {
    id: 171,
    name: "Mattel HyperScan",
  },
  {
    id: 172,
    name: "Game Wave Family Entertainment System",
  },
  {
    id: 173,
    name: "Sega CD 32X",
  },
  {
    id: 174,
    name: "Aamber Pegasus",
  },
  {
    id: 175,
    name: "Apogee BK-01",
  },
  {
    id: 180,
    name: "Commodore MAX Machine",
  },
  {
    id: 181,
    name: "Commodore PET",
  },
  {
    id: 183,
    name: "Exelvision EXL 100",
  },
  {
    id: 184,
    name: "Exidy Sorcerer",
  },
  {
    id: 186,
    name: "Fujitsu FM-7",
  },
  {
    id: 187,
    name: "Hector HRX",
  },
  {
    id: 189,
    name: "Matra and Hachette Alice",
  },
  {
    id: 190,
    name: "Microsoft MSX2",
  },
  {
    id: 191,
    name: "Microsoft MSX2&#x2B;",
  },
  {
    id: 192,
    name: "NEC PC-8801",
  },
  {
    id: 193,
    name: "NEC PC-9801",
  },
  {
    id: 194,
    name: "Nintendo 64DD",
  },
  {
    id: 195,
    name: "Nintendo Pokemon Mini",
  },
  {
    id: 197,
    name: "Othello Multivision",
  },
  {
    id: 198,
    name: "VTech Socrates",
  },
  {
    id: 199,
    name: "Vector-06C",
  },
  {
    id: 200,
    name: "Tomy Tutor",
  },
  {
    id: 201,
    name: "Spectravideo",
  },
  {
    id: 202,
    name: "Sony PSP Minis",
  },
  {
    id: 203,
    name: "Sony PocketStation",
  },
  {
    id: 204,
    name: "Sharp X1",
  },
  {
    id: 205,
    name: "Sharp MZ-2500",
  },
  {
    id: 207,
    name: "Sega Triforce",
  },
  {
    id: 208,
    name: "Sega Hikaru",
  },
  {
    id: 210,
    name: "SNK Neo Geo MVS",
  },
  {
    id: 211,
    name: "Nintendo Switch",
  },
  {
    id: 212,
    name: "Windows 3.X",
  },
  {
    id: 213,
    name: "Nokia N-Gage",
  },
  {
    id: 216,
    name: "GameWave",
  },
  {
    id: 218,
    name: "Linux",
  },
  {
    id: 219,
    name: "Sony Playstation 5",
  },
  {
    id: 220,
    name: "PICO-8",
  },
  {
    id: 221,
    name: "VTech V.Smile",
  },
  {
    id: 222,
    name: "Microsoft Xbox Series X/S",
  },
  {
    id: 223,
    name: "Bandai Super Vision 8000",
  },
  {
    id: 224,
    name: "Nintendo Switch 2",
  },
  {
    id: 225,
    name: "Elektor TV Games Computer",
  },
  {
    id: 226,
    name: "Arduboy",
  },
  {
    id: 227,
    name: "Uzebox",
  },
  {
    id: 228,
    name: "WASM-4",
  },
] as const satisfies readonly LaunchBoxPlatformReference[];
