import { describe, expect, it } from "vitest";

import {
  isLiveFoilMaskOverride,
  liveFoilMaskFromMap,
  liveLaminatePreferFromMap,
} from "./liveFoilMasks";
import { paperMaterial } from "./materials";

/*
  Fixtures, not local data: these tests pin the lookup rules. The real map
  lives in `data/pokemon/liveFoilMasks.json` and is regenerated by the pack
  pipeline — data drift must not break unit tests (data audits live in
  foilLayerAudit.test.ts behind skipIf guards).
*/
const CHARKOS = { "me5_fr_045::std": "CastAndCure" };
const BOTH_LAMINATES = {
  "rsv10-5_de_001::sph": "ReverseLaminatePokeBall",
  "rsv10-5_de_001::mph": "ReverseLaminateMasterBall",
};
const MPH_ONLY = { "rsv10-5_fr_044::mph": "ReverseLaminateMasterBall" };

describe("liveFoilMaskFromMap", () => {
  it("maps Charkos-ex std → CastAndCure", () => {
    expect(liveFoilMaskFromMap(CHARKOS, "me5_fr_045", { variant: "std" })).toBe(
      "CastAndCure",
    );
    // Unknown variant still finds CastAndCure on the stem (playroom seed).
    expect(liveFoilMaskFromMap(CHARKOS, "me5_fr_045")).toBe("CastAndCure");
  });

  it("distingue Poké Ball vs Master Ball sur le même stem", () => {
    expect(
      liveFoilMaskFromMap(BOTH_LAMINATES, "rsv10-5_de_001", { variant: "sph" }),
    ).toBe("ReverseLaminatePokeBall");
    expect(
      liveFoilMaskFromMap(BOTH_LAMINATES, "rsv10-5_de_001", { variant: "mph" }),
    ).toBe("ReverseLaminateMasterBall");
    // Sans variant / variant dump `ph`: ne pas inventer quand mph+sph coexistent.
    expect(liveFoilMaskFromMap(BOTH_LAMINATES, "rsv10-5_de_001")).toBeNull();
    expect(
      liveFoilMaskFromMap(BOTH_LAMINATES, "rsv10-5_de_001", { variant: "ph" }),
    ).toBeNull();
  });

  it("dump `ph` → Master Ball quand mph est le seul laminate du stem", () => {
    expect(
      liveFoilMaskFromMap(MPH_ONLY, "rsv10-5_fr_044", { variant: "ph" }),
    ).toBe("ReverseLaminateMasterBall");
    expect(liveFoilMaskFromMap(MPH_ONLY, "rsv10-5_fr_044")).toBe(
      "ReverseLaminateMasterBall",
    );
    expect(liveLaminatePreferFromMap(MPH_ONLY, "rsv10-5_fr_044")).toBe("mph");
  });

  it("ne choisit jamais entre mph et sph (ambiguïté → null)", () => {
    expect(
      liveLaminatePreferFromMap(BOTH_LAMINATES, "rsv10-5_de_001"),
    ).toBeNull();
  });

  it("returns null for ordinary reverse / holo stems", () => {
    expect(
      liveFoilMaskFromMap(CHARKOS, "bw10_fr_001", { variant: "ph" }),
    ).toBeNull();
    expect(liveFoilMaskFromMap(CHARKOS, null)).toBeNull();
  });

  it("allume UseCCFoil sur le material SunPillar de Charkos", () => {
    const mask = liveFoilMaskFromMap(CHARKOS, "me5_fr_045", { variant: "std" });
    expect(
      paperMaterial("SunPillar", { foilMask: mask })!.floats._UseCCFoil,
    ).toBe(1);
  });

  it("isLiveFoilMaskOverride", () => {
    expect(isLiveFoilMaskOverride("CastAndCure")).toBe(true);
    expect(isLiveFoilMaskOverride("Reverse")).toBe(false);
  });
});
