import { beforeEach, describe, expect, it, vi } from "vitest";

/*
  Hermetic: preferForLiveOpen's rules are pinned against mocked lookups. The
  real data (card_foil sqlite + liveFoilMasks.json) is regenerated by the pack
  pipeline — data drift must not break unit tests.
*/
const liveLaminatePreferForBundle = vi.fn();
const variantsForBundle = vi.fn();

vi.mock("@/effects/pokemon/liveFoilMasks", async (importOriginal) => {
  const actual =
    await importOriginal<typeof import("@/effects/pokemon/liveFoilMasks")>();
  return {
    ...actual,
    liveLaminatePreferForBundle: (...args: unknown[]) =>
      liveLaminatePreferForBundle(...args),
  };
});
vi.mock("@/effects/pokemon/cardFoilLookups", async (importOriginal) => {
  const actual =
    await importOriginal<typeof import("@/effects/pokemon/cardFoilLookups")>();
  return {
    ...actual,
    variantsForBundle: (...args: unknown[]) => variantsForBundle(...args),
  };
});

import { preferForLiveOpen } from "@/lib/admin/liveOpen";

beforeEach(() => {
  liveLaminatePreferForBundle.mockReset().mockReturnValue(null);
  variantsForBundle.mockReset().mockReturnValue([]);
});

describe("preferForLiveOpen", () => {
  it("laminate prefer (mph/sph) wins over the dump ph", () => {
    liveLaminatePreferForBundle.mockReturnValue("mph");
    variantsForBundle.mockReturnValue([
      { variant: "std", shader: "NonFoil" },
      { variant: "ph", shader: "FlatSilver" },
    ]);
    expect(preferForLiveOpen("rsv10-5_fr_044", "FlatSilver")).toBe("mph");
  });

  it("prefers ph when that variant carries the material", () => {
    variantsForBundle.mockReturnValue([
      { variant: "std", shader: "NonFoil" },
      { variant: "ph", shader: "AngledPillars" },
    ]);
    expect(preferForLiveOpen("ec_fr_010", "AngledPillars")).toBe("ph");
  });

  it("keeps std when no foil variant carries the material", () => {
    variantsForBundle.mockReturnValue([{ variant: "std", shader: "NonFoil" }]);
    expect(preferForLiveOpen("smalt_fr_001", "AngledPillars")).toBe("");
  });

  it("keeps std when the bundle is unknown", () => {
    expect(preferForLiveOpen("unknown_000", "FlatSilver")).toBe("");
  });
});
